In [84]:
import pandas as pd

In [85]:
df_housing=pd.read_csv("housing.csv")

In [86]:
df_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [87]:
df_housing.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [88]:
df_housing.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [89]:
median=df_housing['total_bedrooms'].median()

In [90]:
df_housing['total_bedrooms']=df_housing['total_bedrooms'].fillna(median)

In [91]:
df_housing['total_bedrooms'].isnull().sum()

np.int64(0)

In [92]:
df_housing=pd.get_dummies(df_housing,columns=['ocean_proximity'])

In [93]:
df_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,False,False,False,True,False
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,False,False,False,True,False
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,False,False,False,True,False
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,False,False,False,True,False
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,False,True,False,False,False
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,False,True,False,False,False
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,False,True,False,False,False
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,False,True,False,False,False
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,False,True,False,False,False

In [94]:
ocean_cols = [
    'ocean_proximity_<1H OCEAN',
    'ocean_proximity_INLAND',
    'ocean_proximity_ISLAND',
    'ocean_proximity_NEAR BAY',
    'ocean_proximity_NEAR OCEAN'
]

df_housing[ocean_cols]=df_housing[ocean_cols].astype(int)

In [95]:
df_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,0,0,0,1,0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,0,0,0,1,0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,0,0,0,1,0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,0,0,0,1,0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,0,1,0,0,0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,0,1,0,0,0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,0,1,0,0,0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,0,1,0,0,0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,0,1,0,0,0

In [96]:
from sklearn.model_selection import train_test_split

features=['longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income']+ocean_cols

X=df_housing[features]
y=df_housing['median_house_value']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

print(X_train.shape)
print(X_test.shape)

(16512, 13)
(4128, 13)

In [97]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)    
X_test = scaler.transform(X_test)

BASE LINE with 30 Epochs and batch size is 30

In [98]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

# Model 1: Baseline MLP (Modern & Clean Way)
model_baseline = Sequential([
    Input(shape=(X_train.shape[1],)),  # Yeh pehli line mein input define kar diya
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)  # Regression ke liye 1 output
])

model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
history_baseline = model_baseline.fit(X_train, y_train, validation_split=0.2, epochs=30, batch_size=30, verbose=1)

Epoch 1/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 55966347264.0000 - mae: 206615.7344 - val_loss: 56078323712.0000 - val_mae: 206253.9219
Epoch 2/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 53241995264.0000 - mae: 200882.4844 - val_loss: 50685075456.0000 - val_mae: 194861.1875
Epoch 3/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 44863340544.0000 - mae: 182188.5156 - val_loss: 39314092032.0000 - val_mae: 168439.9375
Epoch 4/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 32132753408.0000 - mae: 149564.0156 - val_loss: 25902163968.0000 - val_mae: 130984.7656
Epoch 5/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 20140109824.0000 - mae: 112118.8047 - val_loss: 15893644288.0000 - val_mae: 96264.0703
Epoch 6/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 12903482368.0000 - mae: 86321.6172 - val_loss: 11251853312.0000 - val_mae: 78977.2031
Epoch 7/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 10079213568.0000 - mae: 76103.4141 - val_loss: 9696788480.0000 - val_mae: 73197.7891
Epoch 8/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 9058659328.0000 - mae: 71796.8203 - val_loss: 8960098304.0000 - val_mae: 70173.2891
Epoch 9/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8452712448.0000 - mae: 68784.6484 - val_loss: 8407706624.0000 - val_mae: 67651.2578
Epoch 10/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 7964788224.0000 - mae: 66233.1250 - val_loss: 7941793792.0000 - val_mae: 65416.3945
Epoch 11/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7544631808.0000 - mae: 64021.0820 - val_loss: 7534506496.0000 - val_mae: 63389.7539
Epoch 12/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 7173072896.0000 - mae: 62036.6055 - val_loss: 7173799424.0000 - val_mae: 61508.1016
Epoch 13/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 6842054144.0000 - mae: 60240.9961 - val_loss: 6853548032.0000 - val_mae: 59777.8359
Epoch 14/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 6545977856.0000 - mae: 58617.3008 - val_loss: 6568157696.0000 - val_mae: 58209.4805
Epoch 15/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 6279521280.0000 - mae: 57149.2539 - val_loss: 6313855488.0000 - val_mae: 56823.2227
Epoch 16/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 6040867328.0000 - mae: 55834.6211 - val_loss: 6088623616.0000 - val_mae: 55620.6250
Epoch 17/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 5828542464.0000 - mae: 54679.4375 - val_loss: 5890131456.0000 - val_mae: 54551.8438
Epoch 18/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5641474560.0000 - mae: 53677.4688 - val_loss: 5718256640.0000 - val_mae: 53629.7070
Epoch 19/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5479784960.0000 - mae: 52838.6406 - val_loss: 5571913728.0000 - val_mae: 52858.4727
Epoch 20/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5342202880.0000 - mae: 52142.8398 - val_loss: 5448427520.0000 - val_mae: 52222.4648
Epoch 21/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5226108416.0000 - mae: 51571.1406 - val_loss: 5346024960.0000 - val_mae: 51703.6719
Epoch 22/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 5127830016.0000 - mae: 51101.7695 - val_loss: 5260887040.0000 - val_mae: 51280.4883
Epoch 23/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 5044264448.0000 - mae: 50706.5117 - val_loss: 5190524928.0000 - val_mae: 50937.1602
Epoch 24/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4973688320.0000 - mae: 50376.3438 - val_loss: 5131783680.0000 - val_mae: 50649.2852
Epoch 25/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4913327104.0000 - mae: 50092.0273 - val_loss: 5081522176.0000 - val_mae: 50410.9297
Epoch 26/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4860628480.0000 - mae: 49839.7930 - val_loss: 5037971968.0000 - val_mae: 50205.6055
Epoch 27/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4814292992.0000 - mae: 49614.4336 - val_loss: 4999471104.0000 - val_mae: 50023.4062
Epoch 28/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4773046272.0000 - mae: 49408.5078 - val_loss: 4965543936.0000 - val_mae: 49864.0352
Epoch 29/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4736328704.0000 - mae: 49225.9570 - val_loss: 4935353856.0000 - val_mae: 49724.1133
Epoch 30/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4703333888.0000 - mae: 49059.7656 - val_loss: 4908438016.0000 - val_mae: 49595.8828

BASE LINE WITH 50 EPOCHS AND BATCH SIZE IS 50

In [99]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

# Model 1: Baseline MLP (Modern & Clean Way)
model_baseline = Sequential([
    Input(shape=(X_train.shape[1],)),  # Yeh pehli line mein input define kar diya
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)  # Regression ke liye 1 output
])

model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
history_baseline = model_baseline.fit(X_train, y_train, validation_split=0.2, epochs=50, batch_size=50, verbose=1)

Epoch 1/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 56107909120.0000 - mae: 206916.9062 - val_loss: 56682643456.0000 - val_mae: 207510.7031
Epoch 2/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 55414530048.0000 - mae: 205475.3281 - val_loss: 55245692928.0000 - val_mae: 204553.2188
Epoch 3/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 52964409344.0000 - mae: 200364.6562 - val_loss: 51600564224.0000 - val_mae: 196886.1406
Epoch 4/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 48167120896.0000 - mae: 189955.3750 - val_loss: 45561327616.0000 - val_mae: 183485.9531
Epoch 5/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 41246330880.0000 - mae: 173790.3750 - val_loss: 37780971520.0000 - val_mae: 164653.6719
Epoch 6/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 33164851200.0000 - mae: 152892.0781 - val_loss: 29497563136.0000 - val_mae: 142053.9688
Epoch 7/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 25237235712.0000 - mae: 129374.5859 - val_loss: 22024855552.0000 - val_mae: 118394.2578
Epoch 8/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 18638829568.0000 - mae: 107174.8281 - val_loss: 16332013568.0000 - val_mae: 97920.4141
Epoch 9/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14038033408.0000 - mae: 90699.5469 - val_loss: 12736137216.0000 - val_mae: 84723.0469
Epoch 10/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11371914240.0000 - mae: 81315.8906 - val_loss: 10820219904.0000 - val_mae: 78006.7109
Epoch 11/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10017114112.0000 - mae: 76464.1406 - val_loss: 9850107904.0000 - val_mae: 74499.8828
Epoch 12/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9306420224.0000 - mae: 73576.2188 - val_loss: 9280112640.0000 - val_mae: 72274.1953
Epoch 13/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8848348160.0000 - mae: 71455.7891 - val_loss: 8863925248.0000 - val_mae: 70514.6641
Epoch 14/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8490129408.0000 - mae: 69651.7812 - val_loss: 8518267392.0000 - val_mae: 68941.1250
Epoch 15/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8181986816.0000 - mae: 68039.4297 - val_loss: 8213785600.0000 - val_mae: 67498.4766
Epoch 16/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7906378240.0000 - mae: 66571.6016 - val_loss: 7939307520.0000 - val_mae: 66148.7266
Epoch 17/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7654548992.0000 - mae: 65226.3984 - val_loss: 7688553984.0000 - val_mae: 64888.2383
Epoch 18/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7421458432.0000 - mae: 63974.8242 - val_loss: 7456487936.0000 - val_mae: 63688.4531
Epoch 19/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7204041728.0000 - mae: 62797.3789 - val_loss: 7240593920.0000 - val_mae: 62542.3320
Epoch 20/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7000271360.0000 - mae: 61679.4883 - val_loss: 7038704128.0000 - val_mae: 61439.4180
Epoch 21/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6808608768.0000 - mae: 60615.8008 - val_loss: 6849695744.0000 - val_mae: 60392.4375
Epoch 22/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6627891712.0000 - mae: 59598.1953 - val_loss: 6672331264.0000 - val_mae: 59381.5508
Epoch 23/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6457464832.0000 - mae: 58631.4805 - val_loss: 6506034176.0000 - val_mae: 58427.7852
Epoch 24/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6296687616.0000 - mae: 57711.0742 - val_loss: 6350281728.0000 - val_mae: 57540.7891
Epoch 25/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6145532928.0000 - mae: 56846.0430 - val_loss: 6205075968.0000 - val_mae: 56719.5703
Epoch 26/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6003640832.0000 - mae: 56033.5547 - val_loss: 6069631488.0000 - val_mae: 55955.5156
Epoch 27/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5870803968.0000 - mae: 55273.3477 - val_loss: 5944417280.0000 - val_mae: 55236.4609
Epoch 28/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5747229184.0000 - mae: 54570.0547 - val_loss: 5828819456.0000 - val_mae: 54570.9492
Epoch 29/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5632723968.0000 - mae: 53925.2461 - val_loss: 5722587648.0000 - val_mae: 53959.5859
Epoch 30/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5527192064.0000 - mae: 53339.3164 - val_loss: 5625600512.0000 - val_mae: 53415.3281
Epoch 31/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5430467072.0000 - mae: 52808.9961 - val_loss: 5537580544.0000 - val_mae: 52934.3711
Epoch 32/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5342539776.0000 - mae: 52336.8047 - val_loss: 5458463744.0000 - val_mae: 52504.9961
Epoch 33/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5263638528.0000 - mae: 51920.5156 - val_loss: 5387878912.0000 - val_mae: 52122.2461
Epoch 34/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5193362944.0000 - mae: 51556.0586 - val_loss: 5325596672.0000 - val_mae: 51788.7891
Epoch 35/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5130683392.0000 - mae: 51233.0156 - val_loss: 5270913536.0000 - val_mae: 51486.1641
Epoch 36/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5074408960.0000 - mae: 50948.1523 - val_loss: 5222472704.0000 - val_mae: 51217.1680
Epoch 37/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5023943168.0000 - mae: 50695.2578 - val_loss: 5179458048.0000 - val_mae: 50979.8672
Epoch 38/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4978652672.0000 - mae: 50466.3320 - val_loss: 5141011456.0000 - val_mae: 50770.9062
Epoch 39/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4937724416.0000 - mae: 50257.4609 - val_loss: 5106472960.0000 - val_mae: 50590.8438
Epoch 40/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4900511232.0000 - mae: 50064.5273 - val_loss: 5075203584.0000 - val_mae: 50435.3281
Epoch 41/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4866327552.0000 - mae: 49885.0508 - val_loss: 5046782464.0000 - val_mae: 50294.6562
Epoch 42/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4835018240.0000 - mae: 49720.0859 - val_loss: 5021012480.0000 - val_mae: 50168.2344
Epoch 43/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4806246912.0000 - mae: 49569.1211 - val_loss: 4997451776.0000 - val_mae: 50051.4531
Epoch 44/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4779624960.0000 - mae: 49428.1836 - val_loss: 4975867392.0000 - val_mae: 49940.8555
Epoch 45/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4754950656.0000 - mae: 49295.5273 - val_loss: 4955721216.0000 - val_mae: 49837.0352
Epoch 46/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4731931648.0000 - mae: 49169.9453 - val_loss: 4937033728.0000 - val_mae: 49740.7305
Epoch 47/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4710489600.0000 - mae: 49053.1016 - val_loss: 4919715328.0000 - val_mae: 49650.2734
Epoch 48/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4690605056.0000 - mae: 48944.0312 - val_loss: 4903558656.0000 - val_mae: 49565.9648
Epoch 49/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4671943168.0000 - mae: 48841.1172 - val_loss: 4888425984.0000 - val_mae: 49488.7031
Epoch 50/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4654326784.0000 - mae: 48742.5469 - val_loss: 4874083840.0000 - val_mae: 49418.4453

2) Deeper DNN (MULTIPLE LAYERS)

In [103]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

# Model 1: Baseline MLP (Modern & Clean Way)
model_baseline = Sequential([
    Input(shape=(X_train.shape[1],)),  # Yeh pehli line mein input define kar diya
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1)  # Regression ke liye 1 output
])

model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
history_baseline = model_baseline.fit(X_train, y_train, validation_split=0.2, epochs=50, batch_size=50, verbose=1)

Epoch 1/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48280412160.0000 - mae: 187091.7656 - val_loss: 16584892416.0000 - val_mae: 96786.6797
Epoch 2/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9047964672.0000 - mae: 70435.0312 - val_loss: 7584126464.0000 - val_mae: 62485.1055
Epoch 3/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6655284224.0000 - mae: 58836.7031 - val_loss: 6227844096.0000 - val_mae: 55570.1953
Epoch 4/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5684115968.0000 - mae: 53696.7188 - val_loss: 5558089728.0000 - val_mae: 52095.6211
Epoch 5/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5192256512.0000 - mae: 51247.7656 - val_loss: 5231799808.0000 - val_mae: 50599.0859
Epoch 6/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4929178112.0000 - mae: 50005.0859 - val_loss: 5052478976.0000 - val_mae: 49812.1094
Epoch 7/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4767619072.0000 - mae: 49208.2344 - val_loss: 4934975488.0000 - val_mae: 49282.1172
Epoch 8/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4653310464.0000 - mae: 48612.8555 - val_loss: 4848360960.0000 - val_mae: 48891.5859
Epoch 9/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4565787648.0000 - mae: 48143.2734 - val_loss: 4781542400.0000 - val_mae: 48592.3555
Epoch 10/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4497017856.0000 - mae: 47761.7539 - val_loss: 4728361984.0000 - val_mae: 48362.4180
Epoch 11/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4441578496.0000 - mae: 47444.2188 - val_loss: 4684354560.0000 - val_mae: 48163.9766
Epoch 12/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4396710400.0000 - mae: 47176.2383 - val_loss: 4647937024.0000 - val_mae: 47991.4883
Epoch 13/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4359271936.0000 - mae: 46947.2344 - val_loss: 4617232384.0000 - val_mae: 47839.0977
Epoch 14/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4327747072.0000 - mae: 46749.0039 - val_loss: 4590841344.0000 - val_mae: 47699.2500
Epoch 15/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4300455936.0000 - mae: 46572.9688 - val_loss: 4567290880.0000 - val_mae: 47561.5898
Epoch 16/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4276443392.0000 - mae: 46414.3477 - val_loss: 4546532352.0000 - val_mae: 47429.5234
Epoch 17/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4254861568.0000 - mae: 46270.5352 - val_loss: 4528391168.0000 - val_mae: 47309.3398
Epoch 18/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4235430912.0000 - mae: 46142.0820 - val_loss: 4511774720.0000 - val_mae: 47198.8711
Epoch 19/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4217604096.0000 - mae: 46026.9258 - val_loss: 4496891392.0000 - val_mae: 47095.5859
Epoch 20/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4201356032.0000 - mae: 45922.5430 - val_loss: 4483891712.0000 - val_mae: 47007.0469
Epoch 21/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4186488576.0000 - mae: 45827.9531 - val_loss: 4471533568.0000 - val_mae: 46924.3281
Epoch 22/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4172753920.0000 - mae: 45739.6758 - val_loss: 4460430336.0000 - val_mae: 46845.7969
Epoch 23/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4160043008.0000 - mae: 45658.3320 - val_loss: 4450203136.0000 - val_mae: 46775.0195
Epoch 24/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4148242432.0000 - mae: 45581.1875 - val_loss: 4440754688.0000 - val_mae: 46706.0195
Epoch 25/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4137214208.0000 - mae: 45508.5742 - val_loss: 4431734784.0000 - val_mae: 46642.3047
Epoch 26/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4126809088.0000 - mae: 45441.1523 - val_loss: 4423425536.0000 - val_mae: 46583.7539
Epoch 27/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4116889600.0000 - mae: 45375.4961 - val_loss: 4415450112.0000 - val_mae: 46527.2773
Epoch 28/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4107390208.0000 - mae: 45312.9883 - val_loss: 4407818752.0000 - val_mae: 46470.3477
Epoch 29/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4098350080.0000 - mae: 45252.7695 - val_loss: 4400665088.0000 - val_mae: 46416.4805
Epoch 30/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4089639424.0000 - mae: 45194.7461 - val_loss: 4393625088.0000 - val_mae: 46361.2461
Epoch 31/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4081221888.0000 - mae: 45137.5547 - val_loss: 4387371520.0000 - val_mae: 46311.5430
Epoch 32/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4073244672.0000 - mae: 45083.7031 - val_loss: 4381022208.0000 - val_mae: 46262.7539
Epoch 33/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4065379584.0000 - mae: 45028.8008 - val_loss: 4374998528.0000 - val_mae: 46215.9023
Epoch 34/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4057815808.0000 - mae: 44975.8867 - val_loss: 4369105920.0000 - val_mae: 46168.6406
Epoch 35/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4050248192.0000 - mae: 44922.6055 - val_loss: 4362982912.0000 - val_mae: 46121.5312
Epoch 36/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4042940160.0000 - mae: 44870.9609 - val_loss: 4356958208.0000 - val_mae: 46070.9766
Epoch 37/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4035430656.0000 - mae: 44817.5195 - val_loss: 4350320128.0000 - val_mae: 46020.8047
Epoch 38/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 4027786496.0000 - mae: 44765.8008 - val_loss: 4344220672.0000 - val_mae: 45973.4297
Epoch 39/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4020443392.0000 - mae: 44713.6055 - val_loss: 4338177024.0000 - val_mae: 45924.7031
Epoch 40/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4013103616.0000 - mae: 44661.3203 - val_loss: 4332165120.0000 - val_mae: 45877.1406
Epoch 41/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4005836288.0000 - mae: 44609.4727 - val_loss: 4325880832.0000 - val_mae: 45829.7305
Epoch 42/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3997865216.0000 - mae: 44555.3867 - val_loss: 4319117824.0000 - val_mae: 45777.9336
Epoch 43/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3989854208.0000 - mae: 44496.9648 - val_loss: 4311266304.0000 - val_mae: 45717.9336
Epoch 44/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3980371200.0000 - mae: 44431.9023 - val_loss: 4302835200.0000 - val_mae: 45654.4609
Epoch 45/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3970065152.0000 - mae: 44362.9102 - val_loss: 4293315328.0000 - val_mae: 45585.4141
Epoch 46/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3959087616.0000 - mae: 44288.7109 - val_loss: 4283057920.0000 - val_mae: 45512.4531
Epoch 47/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3947185664.0000 - mae: 44212.3438 - val_loss: 4272695552.0000 - val_mae: 45441.9375
Epoch 48/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3934605056.0000 - mae: 44132.0820 - val_loss: 4261936896.0000 - val_mae: 45367.4219
Epoch 49/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3921481728.0000 - mae: 44049.6758 - val_loss: 4250538752.0000 - val_mae: 45291.3125
Epoch 50/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3907939584.0000 - mae: 43966.8242 - val_loss: 4239112960.0000 - val_mae: 45216.9023

now with 75 epochs with 75 batch size

In [104]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

# Model 1: Baseline MLP (Modern & Clean Way)
model_baseline = Sequential([
    Input(shape=(X_train.shape[1],)),  # Yeh pehli line mein input define kar diya
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1)  # Regression ke liye 1 output
])

model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
history_baseline = model_baseline.fit(X_train, y_train, validation_split=0.2, epochs=75, batch_size=75, verbose=1)

Epoch 1/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 54715539456.0000 - mae: 203809.5312 - val_loss: 47032905728.0000 - val_mae: 186000.8750
Epoch 2/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19130402816.0000 - mae: 104139.5156 - val_loss: 9221332992.0000 - val_mae: 69382.4453
Epoch 3/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7790567424.0000 - mae: 64423.4258 - val_loss: 7154907136.0000 - val_mae: 60032.2852
Epoch 4/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6408843264.0000 - mae: 57243.2344 - val_loss: 6149333504.0000 - val_mae: 54880.5273
Epoch 5/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5662543360.0000 - mae: 53412.4609 - val_loss: 5616521216.0000 - val_mae: 52202.8086
Epoch 6/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5247584768.0000 - mae: 51473.5508 - val_loss: 5322884096.0000 - val_mae: 50829.7930
Epoch 7/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5001923072.0000 - mae: 50357.2305 - val_loss: 5149186560.0000 - val_mae: 50028.0859
Epoch 8/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 4843023360.0000 - mae: 49605.9414 - val_loss: 5032077824.0000 - val_mae: 49487.8516
Epoch 9/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4728579584.0000 - mae: 49025.5898 - val_loss: 4942427648.0000 - val_mae: 49059.3359
Epoch 10/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 4639602688.0000 - mae: 48554.2344 - val_loss: 4871528448.0000 - val_mae: 48714.2695
Epoch 11/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 4568333824.0000 - mae: 48168.3633 - val_loss: 4812736000.0000 - val_mae: 48432.1250
Epoch 12/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4509518336.0000 - mae: 47836.0234 - val_loss: 4763132416.0000 - val_mae: 48197.5664
Epoch 13/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4460265984.0000 - mae: 47551.5117 - val_loss: 4720914432.0000 - val_mae: 47999.6719
Epoch 14/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 4417994752.0000 - mae: 47300.0039 - val_loss: 4684322816.0000 - val_mae: 47828.7578
Epoch 15/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 4381732352.0000 - mae: 47080.0156 - val_loss: 4652824576.0000 - val_mae: 47681.0156
Epoch 16/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 4350207488.0000 - mae: 46883.3398 - val_loss: 4624823808.0000 - val_mae: 47539.1836
Epoch 17/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 4322529280.0000 - mae: 46708.2695 - val_loss: 4600507904.0000 - val_mae: 47407.0156
Epoch 18/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 4297907200.0000 - mae: 46549.6289 - val_loss: 4578861568.0000 - val_mae: 47285.9258
Epoch 19/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4275474944.0000 - mae: 46406.3047 - val_loss: 4558825472.0000 - val_mae: 47164.4570
Epoch 20/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4255148800.0000 - mae: 46276.6328 - val_loss: 4540820992.0000 - val_mae: 47057.7227
Epoch 21/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4236431104.0000 - mae: 46157.3438 - val_loss: 4524128768.0000 - val_mae: 46959.0352
Epoch 22/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4219459328.0000 - mae: 46048.1133 - val_loss: 4509442048.0000 - val_mae: 46876.6719
Epoch 23/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 4203905792.0000 - mae: 45948.9805 - val_loss: 4495910400.0000 - val_mae: 46798.8477
Epoch 24/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4189455360.0000 - mae: 45856.8945 - val_loss: 4483095040.0000 - val_mae: 46722.4258
Epoch 25/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4176012032.0000 - mae: 45770.5391 - val_loss: 4471709696.0000 - val_mae: 46652.8398
Epoch 26/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4163430144.0000 - mae: 45690.8750 - val_loss: 4460995072.0000 - val_mae: 46583.7266
Epoch 27/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4151626240.0000 - mae: 45615.6523 - val_loss: 4451149312.0000 - val_mae: 46521.0547
Epoch 28/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 4140477696.0000 - mae: 45543.8594 - val_loss: 4441796608.0000 - val_mae: 46464.3984
Epoch 29/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4130032384.0000 - mae: 45476.2383 - val_loss: 4432869888.0000 - val_mae: 46408.1094
Epoch 30/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4119746816.0000 - mae: 45411.4219 - val_loss: 4424419328.0000 - val_mae: 46357.6289
Epoch 31/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4109633024.0000 - mae: 45347.2773 - val_loss: 4416250880.0000 - val_mae: 46303.9375
Epoch 32/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4099971328.0000 - mae: 45285.8086 - val_loss: 4408583680.0000 - val_mae: 46251.8828
Epoch 33/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4090724096.0000 - mae: 45228.0859 - val_loss: 4401573376.0000 - val_mae: 46202.9922
Epoch 34/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4081968896.0000 - mae: 45172.4062 - val_loss: 4394840576.0000 - val_mae: 46156.9531
Epoch 35/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4073509120.0000 - mae: 45118.6328 - val_loss: 4388259328.0000 - val_mae: 46110.9180
Epoch 36/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4065465344.0000 - mae: 45064.8125 - val_loss: 4381730304.0000 - val_mae: 46062.5078
Epoch 37/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4057651712.0000 - mae: 45013.6133 - val_loss: 4375911936.0000 - val_mae: 46019.1953
Epoch 38/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4050179584.0000 - mae: 44962.1641 - val_loss: 4370124800.0000 - val_mae: 45976.5742
Epoch 39/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4042811904.0000 - mae: 44911.3242 - val_loss: 4364589568.0000 - val_mae: 45936.8672
Epoch 40/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4035577856.0000 - mae: 44861.0117 - val_loss: 4359104512.0000 - val_mae: 45895.8672
Epoch 41/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4028265984.0000 - mae: 44811.4297 - val_loss: 4353824768.0000 - val_mae: 45856.8711
Epoch 42/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4021103360.0000 - mae: 44761.9805 - val_loss: 4348507136.0000 - val_mae: 45816.8398
Epoch 43/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4014041088.0000 - mae: 44713.7031 - val_loss: 4343069696.0000 - val_mae: 45773.7461
Epoch 44/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 4007086592.0000 - mae: 44665.6484 - val_loss: 4337911808.0000 - val_mae: 45733.9961
Epoch 45/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3999968000.0000 - mae: 44616.7266 - val_loss: 4332827648.0000 - val_mae: 45694.6914
Epoch 46/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3992929536.0000 - mae: 44568.3281 - val_loss: 4327425024.0000 - val_mae: 45652.8203
Epoch 47/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3985914880.0000 - mae: 44518.6016 - val_loss: 4322055680.0000 - val_mae: 45608.6094
Epoch 48/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3978979328.0000 - mae: 44468.8477 - val_loss: 4316601344.0000 - val_mae: 45564.4922
Epoch 49/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3971895040.0000 - mae: 44418.5273 - val_loss: 4311422464.0000 - val_mae: 45520.4844
Epoch 50/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3964778240.0000 - mae: 44368.9688 - val_loss: 4306314752.0000 - val_mae: 45479.9258
Epoch 51/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3957711872.0000 - mae: 44318.0938 - val_loss: 4300691968.0000 - val_mae: 45433.8672
Epoch 52/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3950527488.0000 - mae: 44266.7188 - val_loss: 4295310336.0000 - val_mae: 45388.3086
Epoch 53/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 3943398400.0000 - mae: 44216.2930 - val_loss: 4289782784.0000 - val_mae: 45344.2227
Epoch 54/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3936150016.0000 - mae: 44164.7383 - val_loss: 4284198144.0000 - val_mae: 45297.7188
Epoch 55/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3928946432.0000 - mae: 44112.6133 - val_loss: 4278478336.0000 - val_mae: 45250.1562
Epoch 56/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3921648128.0000 - mae: 44059.3906 - val_loss: 4272747520.0000 - val_mae: 45203.2891
Epoch 57/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3914241536.0000 - mae: 44006.8984 - val_loss: 4267070720.0000 - val_mae: 45159.0078
Epoch 58/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3906718464.0000 - mae: 43953.5859 - val_loss: 4261201664.0000 - val_mae: 45112.7891
Epoch 59/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3899105536.0000 - mae: 43898.7344 - val_loss: 4255316992.0000 - val_mae: 45066.4922
Epoch 60/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3891271936.0000 - mae: 43842.1523 - val_loss: 4249201920.0000 - val_mae: 45018.7070
Epoch 61/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3883334144.0000 - mae: 43784.9727 - val_loss: 4243181056.0000 - val_mae: 44970.5703
Epoch 62/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3875218944.0000 - mae: 43725.4180 - val_loss: 4236803840.0000 - val_mae: 44918.4492
Epoch 63/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3866873600.0000 - mae: 43665.0156 - val_loss: 4230190592.0000 - val_mae: 44866.9062
Epoch 64/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3858325248.0000 - mae: 43602.9336 - val_loss: 4223453952.0000 - val_mae: 44812.0469
Epoch 65/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3849422080.0000 - mae: 43536.9336 - val_loss: 4216243200.0000 - val_mae: 44753.7188
Epoch 66/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3839859456.0000 - mae: 43466.0547 - val_loss: 4208512000.0000 - val_mae: 44688.3906
Epoch 67/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3829775872.0000 - mae: 43388.1836 - val_loss: 4199883008.0000 - val_mae: 44615.5195
Epoch 68/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3818803200.0000 - mae: 43306.9023 - val_loss: 4191314176.0000 - val_mae: 44542.7305
Epoch 69/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3807512320.0000 - mae: 43223.0039 - val_loss: 4182345216.0000 - val_mae: 44466.9492
Epoch 70/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3796070656.0000 - mae: 43138.3438 - val_loss: 4172687360.0000 - val_mae: 44387.1094
Epoch 71/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3783602176.0000 - mae: 43051.0039 - val_loss: 4162338816.0000 - val_mae: 44309.2070
Epoch 72/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3770550272.0000 - mae: 42961.4570 - val_loss: 4151975168.0000 - val_mae: 44233.2773
Epoch 73/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3757152768.0000 - mae: 42871.8984 - val_loss: 4141283840.0000 - val_mae: 44155.9727
Epoch 74/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3743367168.0000 - mae: 42779.4375 - val_loss: 4131106048.0000 - val_mae: 44085.3672
Epoch 75/75
177/177 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3729229312.0000 - mae: 42688.4297 - val_loss: 4120430592.0000 - val_mae: 44010.9414

3)Regularised DNN

In [107]:
from tensorflow.keras.layers import Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping

# Model 3: Regularised DNN
model_regularised = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    BatchNormalization(),
    Dropout(0.1), # 30% neurons drop kar dega taake overfit na ho
    Dense(32, activation='relu'),
    BatchNormalization(),
    Dropout(0.2),
    Dense(1)
])

model_regularised.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# Early stopping callback
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

history_reg = model_regularised.fit(
    X_train, y_train, 
    validation_split=0.2, 
    epochs=50, 
    batch_size=32, 
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/50

c:\syed_taha\ds-october-2026\week2\.venv\Lib\site-packages\keras\src\layers\core\dense.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 56148996096.0000 - mae: 207011.0469 - val_loss: 56863985664.0000 - val_mae: 207903.6250
Epoch 2/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 56130621440.0000 - mae: 206986.4688 - val_loss: 56839348224.0000 - val_mae: 207871.5156
Epoch 3/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 56098045952.0000 - mae: 206938.2969 - val_loss: 56800124928.0000 - val_mae: 207812.6250
Epoch 4/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 56052768768.0000 - mae: 206868.6406 - val_loss: 56749662208.0000 - val_mae: 207734.2188
Epoch 5/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 55996399616.0000 - mae: 206780.0000 - val_loss: 56689815552.0000 - val_mae: 207641.1250
Epoch 6/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 55929229312.0000 - mae: 206673.2188 - val_loss: 56615866368.0000 - val_mae: 207525.6719
Epoch 7/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 55852797952.0000 - mae: 206550.4844 - val_loss: 56523886592.0000 - val_mae: 207372.0781
Epoch 8/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 55768256512.0000 - mae: 206414.3906 - val_loss: 56440856576.0000 - val_mae: 207244.2656
Epoch 9/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 55674740736.0000 - mae: 206263.1250 - val_loss: 56338124800.0000 - val_mae: 207074.7656
Epoch 10/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 55574691840.0000 - mae: 206099.7031 - val_loss: 56243175424.0000 - val_mae: 206923.2969
Epoch 11/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 55466209280.0000 - mae: 205921.6250 - val_loss: 56119508992.0000 - val_mae: 206725.6719
Epoch 12/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 55349489664.0000 - mae: 205730.7969 - val_loss: 56012001280.0000 - val_mae: 206552.3125
Epoch 13/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 55224999936.0000 - mae: 205526.6562 - val_loss: 55877812224.0000 - val_mae: 206329.1562
Epoch 14/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 55099564032.0000 - mae: 205318.8594 - val_loss: 55727190016.0000 - val_mae: 206079.4219
Epoch 15/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 54958043136.0000 - mae: 205083.5469 - val_loss: 55594278912.0000 - val_mae: 205860.7969
Epoch 16/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54815203328.0000 - mae: 204847.9219 - val_loss: 55437058048.0000 - val_mae: 205598.0156
Epoch 17/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 54663749632.0000 - mae: 204597.3594 - val_loss: 55313641472.0000 - val_mae: 205412.8906
Epoch 18/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 54506790912.0000 - mae: 204334.9375 - val_loss: 55111376896.0000 - val_mae: 205069.2344
Epoch 19/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54348935168.0000 - mae: 204064.9844 - val_loss: 54985846784.0000 - val_mae: 204861.5000
Epoch 20/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 54179770368.0000 - mae: 203784.5625 - val_loss: 54773276672.0000 - val_mae: 204502.5781
Epoch 21/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 54000099328.0000 - mae: 203485.6406 - val_loss: 54608228352.0000 - val_mae: 204225.0625
Epoch 22/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 53814685696.0000 - mae: 203176.0625 - val_loss: 54429765632.0000 - val_mae: 203929.7500
Epoch 23/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 53619322880.0000 - mae: 202846.2812 - val_loss: 54209740800.0000 - val_mae: 203564.1406
Epoch 24/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 53428035584.0000 - mae: 202521.1562 - val_loss: 54005604352.0000 - val_mae: 203212.5938
Epoch 25/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53233135616.0000 - mae: 202184.3125 - val_loss: 53794791424.0000 - val_mae: 202852.4219
Epoch 26/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53019783168.0000 - mae: 201821.3594 - val_loss: 53644001280.0000 - val_mae: 202648.3906
Epoch 27/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52809310208.0000 - mae: 201464.3594 - val_loss: 53356830720.0000 - val_mae: 202103.9219
Epoch 28/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52591681536.0000 - mae: 201090.9688 - val_loss: 53150093312.0000 - val_mae: 201748.2500
Epoch 29/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52365484032.0000 - mae: 200702.3750 - val_loss: 52877045760.0000 - val_mae: 201272.2656
Epoch 30/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52128956416.0000 - mae: 200302.0000 - val_loss: 52745564160.0000 - val_mae: 201113.6875
Epoch 31/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51885023232.0000 - mae: 199878.7812 - val_loss: 52414713856.0000 - val_mae: 200548.8594
Epoch 32/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51646763008.0000 - mae: 199463.1094 - val_loss: 52112277504.0000 - val_mae: 199962.8125
Epoch 33/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51407548416.0000 - mae: 199044.6250 - val_loss: 51942408192.0000 - val_mae: 199712.3906
Epoch 34/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51143401472.0000 - mae: 198589.3906 - val_loss: 51701202944.0000 - val_mae: 199293.1250
Epoch 35/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50888896512.0000 - mae: 198135.1562 - val_loss: 51425198080.0000 - val_mae: 198843.5312
Epoch 36/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50616209408.0000 - mae: 197659.1875 - val_loss: 51114844160.0000 - val_mae: 198214.0625
Epoch 37/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50359599104.0000 - mae: 197206.5312 - val_loss: 50792542208.0000 - val_mae: 197705.7031
Epoch 38/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50073546752.0000 - mae: 196705.2344 - val_loss: 50506743808.0000 - val_mae: 197185.2812
Epoch 39/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49797488640.0000 - mae: 196212.0781 - val_loss: 50247692288.0000 - val_mae: 196670.3750
Epoch 40/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49518956544.0000 - mae: 195717.9062 - val_loss: 49842266112.0000 - val_mae: 195958.7344
Epoch 41/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49224196096.0000 - mae: 195194.5625 - val_loss: 49709150208.0000 - val_mae: 195652.8125
Epoch 42/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48921133056.0000 - mae: 194649.4375 - val_loss: 49397886976.0000 - val_mae: 195230.4219
Epoch 43/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48636305408.0000 - mae: 194129.6875 - val_loss: 49000665088.0000 - val_mae: 194435.0156
Epoch 44/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48326619136.0000 - mae: 193572.3906 - val_loss: 48737079296.0000 - val_mae: 193987.3281
Epoch 45/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48007340032.0000 - mae: 192990.8594 - val_loss: 48447373312.0000 - val_mae: 193533.1719
Epoch 46/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 47710195712.0000 - mae: 192437.6875 - val_loss: 48054308864.0000 - val_mae: 192724.3594
Epoch 47/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 47366615040.0000 - mae: 191821.5938 - val_loss: 47846539264.0000 - val_mae: 192450.6562
Epoch 48/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 47047356416.0000 - mae: 191235.1719 - val_loss: 47498768384.0000 - val_mae: 191863.2344
Epoch 49/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 46725349376.0000 - mae: 190635.1719 - val_loss: 46941675520.0000 - val_mae: 190632.4375
Epoch 50/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 46410256384.0000 - mae: 190067.1250 - val_loss: 46751817728.0000 - val_mae: 190301.1406

In [113]:
import mlflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, Input
from tensorflow.keras.callbacks import EarlyStopping

# 1. MLflow Experiment Set karein
mlflow.set_experiment("w2-syed-taha")
mlflow.autolog()

# ==========================================
# 1. BASELINE MLP
# ==========================================
with mlflow.start_run(run_name="mlp-baseline"):
    model_baseline = Sequential([
        Input(shape=(X_train.shape[1],)),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(1)
    ])
    model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    
    history_baseline = model_baseline.fit(
        X_train, y_train, 
        validation_split=0.2, 
        epochs=30, 
        batch_size=30, 
        verbose=1
    )
    mlflow.log_param("model_type", "Baseline MLP")


# ==========================================
# 2. DEEPER DNN
# ==========================================
with mlflow.start_run(run_name="mlp-deeper"):
    model_deeper = Sequential([
        Input(shape=(X_train.shape[1],)),
        Dense(128, activation='relu'),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(16, activation='relu'),
        Dense(1)
    ])
    model_deeper.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    
    history_deeper = model_deeper.fit(
        X_train, y_train, 
        validation_split=0.2, 
        epochs=50, 
        batch_size=50, 
        verbose=1
    )
    mlflow.log_param("model_type", "Deeper DNN")


# ==========================================
# 3. REGULARISED DNN
# ==========================================
with mlflow.start_run(run_name="mlp-regularised"):
    model_regularised = Sequential([
        Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        BatchNormalization(),
        Dropout(0.1),
        Dense(32, activation='relu'),
        BatchNormalization(),
        Dropout(0.2),
        Dense(1)
    ])
    model_regularised.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    
    early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
    
    history_reg = model_regularised.fit(
        X_train, y_train, 
        validation_split=0.2, 
        epochs=50, 
        batch_size=32, 
        callbacks=[early_stop],
        verbose=1
    )
    mlflow.log_param("model_type", "Regularised DNN")

print("All three models have successfully run and been logged in MLflow!")

2026/10/18 18:35:50 WARNING mlflow.utils.autologging_utils: MLflow keras autologging is known to be compatible with 3.7.0 <= keras, but the installed version is 3.16.0.dev2026101803. If you encounter errors during autologging, try upgrading / downgrading keras to a compatible version, or try upgrading MLflow.
2026/10/18 18:35:50 INFO mlflow.tracking.fluent: Autologging successfully enabled for keras.
2026/10/18 18:35:51 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2026/10/18 18:35:51 WARNING mlflow.utils.autologging_utils: MLflow tensorflow autologging is known to be compatible with 2.17.1 <= tensorflow, but the installed version is 2.22.0-rc0. If you encounter errors during autologging, try upgrading / downgrading tensorflow to a compatible version, or try upgrading MLflow.
2026/10/18 18:35:51 INFO mlflow.tracking.fluent: Autologging successfully enabled for tensorflow.
2026/10/18 18:35:51 WARNING mlflow.tensorflow: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'

Epoch 1/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56003715072.0000 - mae: 206697.4062

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 56003715072.0000 - mae: 206697.4062 - val_loss: 56235073536.0000 - val_mae: 206589.1719
Epoch 2/30
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 53814648832.0000 - mae: 202136.6719

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 53784502272.0000 - mae: 202056.4844 - val_loss: 51824971776.0000 - val_mae: 197368.0312
Epoch 3/30
430/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 47035011072.0000 - mae: 187246.8281

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 46764539904.0000 - mae: 186647.8594 - val_loss: 42087936000.0000 - val_mae: 175195.5000
Epoch 4/30
424/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 35795083264.0000 - mae: 159348.0312

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 35442737152.0000 - mae: 158381.8594 - val_loss: 29646352384.0000 - val_mae: 141639.6406
Epoch 5/30
411/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 24126662656.0000 - mae: 124810.6953

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 23721842688.0000 - mae: 123489.9688 - val_loss: 19231197184.0000 - val_mae: 108044.8281
Epoch 6/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 15651133440.0000 - mae: 96729.8906

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 15651133440.0000 - mae: 96729.8906 - val_loss: 13566781440.0000 - val_mae: 88433.8047
Epoch 7/30
413/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12007196672.0000 - mae: 84367.1641

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 11878716416.0000 - mae: 83842.1406 - val_loss: 11291953152.0000 - val_mae: 80178.1641
Epoch 8/30
405/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10454118400.0000 - mae: 78283.0234

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10339419136.0000 - mae: 77792.8281 - val_loss: 10228333568.0000 - val_mae: 75714.3203
Epoch 9/30
411/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9562710016.0000 - mae: 74074.1094

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9486343168.0000 - mae: 73757.3984 - val_loss: 9486580736.0000 - val_mae: 72329.1875
Epoch 10/30
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8867679232.0000 - mae: 70529.3047

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 8845473792.0000 - mae: 70444.8828 - val_loss: 8882056192.0000 - val_mae: 69455.1016
Epoch 11/30
418/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8365720576.0000 - mae: 67890.6406

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8311242240.0000 - mae: 67652.9219 - val_loss: 8363662336.0000 - val_mae: 66966.8281
Epoch 12/30
428/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7883337216.0000 - mae: 65422.5391

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7848681984.0000 - mae: 65262.9648 - val_loss: 7910754304.0000 - val_mae: 64764.0898
Epoch 13/30
412/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7493592576.0000 - mae: 63329.6055

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7440344064.0000 - mae: 63143.2031 - val_loss: 7509596672.0000 - val_mae: 62771.8281
Epoch 14/30
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7079693824.0000 - mae: 61259.1094

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7074997760.0000 - mae: 61239.5586 - val_loss: 7152359936.0000 - val_mae: 60971.8047
Epoch 15/30
409/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6774952960.0000 - mae: 59595.1875

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6746148352.0000 - mae: 59516.7539 - val_loss: 6831662592.0000 - val_mae: 59320.2969
Epoch 16/30
435/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6463232000.0000 - mae: 58023.2539

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6450610176.0000 - mae: 57959.1523 - val_loss: 6547204608.0000 - val_mae: 57840.1172
Epoch 17/30
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6207229952.0000 - mae: 56655.9570

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6187621376.0000 - mae: 56564.2812 - val_loss: 6296911872.0000 - val_mae: 56533.6484
Epoch 18/30
440/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5958034432.0000 - mae: 55347.4297

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5955657728.0000 - mae: 55337.8242 - val_loss: 6077772288.0000 - val_mae: 55400.0352
Epoch 19/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5753238528.0000 - mae: 54292.5547

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5753238528.0000 - mae: 54292.5547 - val_loss: 5887801344.0000 - val_mae: 54431.2930
Epoch 20/30
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5589059072.0000 - mae: 53452.2109

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 5578395648.0000 - mae: 53404.8789 - val_loss: 5725167616.0000 - val_mae: 53623.9102
Epoch 21/30
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5437734400.0000 - mae: 52695.2578

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5427799552.0000 - mae: 52651.8281 - val_loss: 5586473984.0000 - val_mae: 52938.9414
Epoch 22/30
434/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5308827648.0000 - mae: 52056.3516

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5298599424.0000 - mae: 52007.3828 - val_loss: 5469521408.0000 - val_mae: 52373.2891
Epoch 23/30
440/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5191169536.0000 - mae: 51476.8242

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5189234176.0000 - mae: 51468.5742 - val_loss: 5371264000.0000 - val_mae: 51903.3164
Epoch 24/30
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5097423360.0000 - mae: 51022.4883

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5096848896.0000 - mae: 51021.2891 - val_loss: 5287934464.0000 - val_mae: 51509.7773
Epoch 25/30
412/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5036175872.0000 - mae: 50706.4492

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 5018067968.0000 - mae: 50644.2305 - val_loss: 5217144832.0000 - val_mae: 51173.3906
Epoch 26/30
433/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4960805888.0000 - mae: 50362.8359

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4950337536.0000 - mae: 50318.7305 - val_loss: 5156130304.0000 - val_mae: 50869.4609
Epoch 27/30
419/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4913532416.0000 - mae: 50135.5977

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4891085312.0000 - mae: 50029.7617 - val_loss: 5102828544.0000 - val_mae: 50604.6641
Epoch 28/30
418/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4853432320.0000 - mae: 49857.2266

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4839117824.0000 - mae: 49773.5352 - val_loss: 5056375296.0000 - val_mae: 50380.2031
Epoch 29/30
430/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4813611008.0000 - mae: 49656.5547

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4793495552.0000 - mae: 49547.1836 - val_loss: 5015691776.0000 - val_mae: 50180.6680
Epoch 30/30
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4759762944.0000 - mae: 49376.6719

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4753136640.0000 - mae: 49346.0117 - val_loss: 4980102144.0000 - val_mae: 50003.1953
WARNING:tensorflow:5 out of the last 1294 calls to <function Trainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x00000201588A31C0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:5 out of the last 1294 calls to <function Trainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x00000201588A31C0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

2026/10/18 18:36:36 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/10/18 18:36:37 INFO mlflow.utils.uv_utils: Detected uv project: found uv.lock and pyproject.toml in c:\syed_taha\ds-october-2026\week2
2026/10/18 18:36:37 INFO mlflow.utils.environment: Detected uv project at c:\syed_taha\ds-october-2026\week2. Attempting to export requirements via 'uv export'.
2026/10/18 18:36:37 INFO mlflow.utils.uv_utils: Exported 141 dependencies via uv
2026/10/18 18:36:37 INFO mlflow.utils.environment: Successfully exported 141 requirements from uv project. Skipping package capture based inference.
2026/10/18 18:36:37 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/10/18 18:36:37 WARNING mlflow.tensorflow: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'

Epoch 1/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 46425047040.0000 - mae: 181592.4531

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 46425047040.0000 - mae: 181592.4531 - val_loss: 12597741568.0000 - val_mae: 81327.8516
Epoch 2/50
247/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8450896384.0000 - mae: 67849.4922

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8323062784.0000 - mae: 67259.5703 - val_loss: 7171525120.0000 - val_mae: 60383.9961
Epoch 3/50
249/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6375530496.0000 - mae: 57126.5273

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6322881536.0000 - mae: 56898.9648 - val_loss: 5989617152.0000 - val_mae: 54262.7969
Epoch 4/50
262/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5506618368.0000 - mae: 52748.0703

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5494119936.0000 - mae: 52687.1562 - val_loss: 5425323520.0000 - val_mae: 51560.2148
Epoch 5/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5075813888.0000 - mae: 50765.5078

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 5075813888.0000 - mae: 50765.5078 - val_loss: 5143790592.0000 - val_mae: 50323.1836
Epoch 6/50
260/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4857410048.0000 - mae: 49722.2383

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4846495744.0000 - mae: 49671.7773 - val_loss: 4983593472.0000 - val_mae: 49597.1367
Epoch 7/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4701531136.0000 - mae: 48925.9922

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4701531136.0000 - mae: 48925.9922 - val_loss: 4878771200.0000 - val_mae: 49118.8945
Epoch 8/50
249/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4610476032.0000 - mae: 48449.7070

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4599597056.0000 - mae: 48374.2383 - val_loss: 4801930240.0000 - val_mae: 48769.1328
Epoch 9/50
248/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4536479232.0000 - mae: 48027.9570

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4522480128.0000 - mae: 47943.3789 - val_loss: 4741879808.0000 - val_mae: 48492.7930
Epoch 10/50
252/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4483376640.0000 - mae: 47748.7734

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4461937664.0000 - mae: 47589.0469 - val_loss: 4693177856.0000 - val_mae: 48269.2227
Epoch 11/50
260/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4421836800.0000 - mae: 47334.9961

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4412915712.0000 - mae: 47293.5469 - val_loss: 4653664768.0000 - val_mae: 48080.9883
Epoch 12/50
263/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4371195392.0000 - mae: 47021.7734

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4372088320.0000 - mae: 47035.1289 - val_loss: 4619881472.0000 - val_mae: 47911.0820
Epoch 13/50
258/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4355912192.0000 - mae: 46925.2617

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4336709120.0000 - mae: 46806.3594 - val_loss: 4590465024.0000 - val_mae: 47750.1289
Epoch 14/50
242/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4311218176.0000 - mae: 46713.9531

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4305182720.0000 - mae: 46604.6562 - val_loss: 4565012480.0000 - val_mae: 47607.1875
Epoch 15/50
242/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4282717184.0000 - mae: 46534.8477

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4277700864.0000 - mae: 46429.9062 - val_loss: 4542979072.0000 - val_mae: 47474.0625
Epoch 16/50
262/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4261715968.0000 - mae: 46306.7891

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4254337280.0000 - mae: 46280.9297 - val_loss: 4523684864.0000 - val_mae: 47349.6367
Epoch 17/50
249/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4237148672.0000 - mae: 46180.6094

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4233529344.0000 - mae: 46147.3438 - val_loss: 4506382336.0000 - val_mae: 47234.1445
Epoch 18/50
237/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4232112896.0000 - mae: 46186.2305

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4215028736.0000 - mae: 46026.5859 - val_loss: 4490997248.0000 - val_mae: 47126.9023
Epoch 19/50
253/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4210181632.0000 - mae: 46024.6250

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4198412544.0000 - mae: 45919.1992 - val_loss: 4477219328.0000 - val_mae: 47033.9336
Epoch 20/50
248/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4190442496.0000 - mae: 45872.3555

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4183285504.0000 - mae: 45821.8438 - val_loss: 4464726528.0000 - val_mae: 46947.1250
Epoch 21/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4169715712.0000 - mae: 45732.7031

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4169715712.0000 - mae: 45732.7031 - val_loss: 4453600256.0000 - val_mae: 46866.6992
Epoch 22/50
237/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4172336896.0000 - mae: 45804.7422

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4157335808.0000 - mae: 45650.7266 - val_loss: 4443671040.0000 - val_mae: 46796.3711
Epoch 23/50
247/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4148407808.0000 - mae: 45624.5781

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4145890816.0000 - mae: 45576.3828 - val_loss: 4434390016.0000 - val_mae: 46732.8242
Epoch 24/50
251/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4147802624.0000 - mae: 45598.2188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4135282944.0000 - mae: 45505.2773 - val_loss: 4425932800.0000 - val_mae: 46672.1406
Epoch 25/50
262/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4131665408.0000 - mae: 45457.6211

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4125433088.0000 - mae: 45438.8906 - val_loss: 4417864704.0000 - val_mae: 46612.8086
Epoch 26/50
253/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4126810880.0000 - mae: 45478.1992

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4116065792.0000 - mae: 45374.6328 - val_loss: 4410296320.0000 - val_mae: 46554.7344
Epoch 27/50
251/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4119320320.0000 - mae: 45405.2500

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4107023104.0000 - mae: 45313.2109 - val_loss: 4403197440.0000 - val_mae: 46502.2422
Epoch 28/50
259/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4111761920.0000 - mae: 45338.3555

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4098459648.0000 - mae: 45253.6250 - val_loss: 4396764672.0000 - val_mae: 46455.1211
Epoch 29/50
251/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4102402560.0000 - mae: 45289.5625

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4090181120.0000 - mae: 45197.4297 - val_loss: 4390606848.0000 - val_mae: 46408.5195
Epoch 30/50
259/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4095575808.0000 - mae: 45229.1367

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4082350592.0000 - mae: 45143.8438 - val_loss: 4384724480.0000 - val_mae: 46361.8086
Epoch 31/50
250/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4076150528.0000 - mae: 45127.5000

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4074800896.0000 - mae: 45090.0664 - val_loss: 4379142144.0000 - val_mae: 46316.1250
Epoch 32/50
252/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4081653760.0000 - mae: 45167.0195

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4067608320.0000 - mae: 45037.7852 - val_loss: 4373934080.0000 - val_mae: 46269.6328
Epoch 33/50
263/265 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4058383616.0000 - mae: 44963.2188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4060600064.0000 - mae: 44986.2148 - val_loss: 4368826368.0000 - val_mae: 46226.6445
Epoch 34/50
257/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4075942912.0000 - mae: 45067.1523

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4053869312.0000 - mae: 44936.7500 - val_loss: 4364035072.0000 - val_mae: 46182.3555
Epoch 35/50
240/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4047672064.0000 - mae: 44997.3398

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4047152896.0000 - mae: 44885.6875 - val_loss: 4359068672.0000 - val_mae: 46140.3203
Epoch 36/50
251/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4052911616.0000 - mae: 44930.6523

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4040696832.0000 - mae: 44837.7891 - val_loss: 4354396672.0000 - val_mae: 46097.0234
Epoch 37/50
261/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4036967680.0000 - mae: 44813.7383

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4034139392.0000 - mae: 44788.5273 - val_loss: 4349848576.0000 - val_mae: 46056.2852
Epoch 38/50
245/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4020949504.0000 - mae: 44801.0430

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4027703296.0000 - mae: 44740.8789 - val_loss: 4345180160.0000 - val_mae: 46014.7344
Epoch 39/50
253/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4031796736.0000 - mae: 44799.5586

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4021285888.0000 - mae: 44693.1094 - val_loss: 4340617216.0000 - val_mae: 45974.7734
Epoch 40/50
237/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4027978496.0000 - mae: 44795.4258

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4014964992.0000 - mae: 44644.7305 - val_loss: 4335923712.0000 - val_mae: 45931.9570
Epoch 41/50
241/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4006708224.0000 - mae: 44688.6875

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4008728320.0000 - mae: 44596.6172 - val_loss: 4331087360.0000 - val_mae: 45889.4805
Epoch 42/50
245/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3995756544.0000 - mae: 44610.4648

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4002372608.0000 - mae: 44549.8242 - val_loss: 4326631424.0000 - val_mae: 45850.6367
Epoch 43/50
245/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3989698048.0000 - mae: 44563.8164

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3996342272.0000 - mae: 44503.2852 - val_loss: 4321681920.0000 - val_mae: 45809.7070
Epoch 44/50
245/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3983727616.0000 - mae: 44519.6836

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3990368000.0000 - mae: 44459.2734 - val_loss: 4317367808.0000 - val_mae: 45772.2852
Epoch 45/50
258/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4000265472.0000 - mae: 44527.3555

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3984346112.0000 - mae: 44414.3633 - val_loss: 4312362496.0000 - val_mae: 45730.0586
Epoch 46/50
263/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3975632384.0000 - mae: 44345.0273

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3978386688.0000 - mae: 44370.7070 - val_loss: 4307943936.0000 - val_mae: 45696.4375
Epoch 47/50
246/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3971499520.0000 - mae: 44371.5625

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3972212992.0000 - mae: 44325.7969 - val_loss: 4303271936.0000 - val_mae: 45658.1133
Epoch 48/50
235/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3988268800.0000 - mae: 44498.0469

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3966256384.0000 - mae: 44281.8398 - val_loss: 4298584576.0000 - val_mae: 45618.6562
Epoch 49/50
257/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3980430848.0000 - mae: 44360.8125

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3959985664.0000 - mae: 44235.4492 - val_loss: 4293830400.0000 - val_mae: 45576.9414
Epoch 50/50
262/265 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3958257408.0000 - mae: 44198.9609

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3953945856.0000 - mae: 44190.3047 - val_loss: 4289002752.0000 - val_mae: 45537.9727
WARNING:tensorflow:6 out of the last 1295 calls to <function Trainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000020142CA49E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:6 out of the last 1295 calls to <function Trainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000020142CA49E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

2026/10/18 18:37:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/10/18 18:37:14 INFO mlflow.utils.uv_utils: Detected uv project: found uv.lock and pyproject.toml in c:\syed_taha\ds-october-2026\week2
2026/10/18 18:37:14 INFO mlflow.utils.environment: Detected uv project at c:\syed_taha\ds-october-2026\week2. Attempting to export requirements via 'uv export'.
2026/10/18 18:37:14 INFO mlflow.utils.uv_utils: Exported 141 dependencies via uv
2026/10/18 18:37:14 INFO mlflow.utils.environment: Successfully exported 141 requirements from uv project. Skipping package capture based inference.
2026/10/18 18:37:14 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
c:\syed_taha\ds-october-2026\week2\.venv\Lib\site-packages\keras\src\layers\core\dense.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026/10/18 18:37:14 WARNING mlflow.tensorflow: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'

Epoch 1/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 56149061632.0000 - mae: 207011.1250

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 56149061632.0000 - mae: 207011.1250 - val_loss: 56864305152.0000 - val_mae: 207903.7812
Epoch 2/50
406/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56262774784.0000 - mae: 207225.6406

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 56130781184.0000 - mae: 206986.8281 - val_loss: 56840347648.0000 - val_mae: 207872.5938
Epoch 3/50
402/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56287051776.0000 - mae: 207288.9531

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 56098332672.0000 - mae: 206938.6562 - val_loss: 56799551488.0000 - val_mae: 207810.3438
Epoch 4/50
391/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56133726208.0000 - mae: 206980.0938

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 56053149696.0000 - mae: 206868.9531 - val_loss: 56747352064.0000 - val_mae: 207730.2500
Epoch 5/50
391/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56077381632.0000 - mae: 206891.7500

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55996608512.0000 - mae: 206780.2500 - val_loss: 56690458624.0000 - val_mae: 207643.8125
Epoch 6/50
412/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55923707904.0000 - mae: 206672.6562

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55929753600.0000 - mae: 206674.0000 - val_loss: 56617979904.0000 - val_mae: 207526.1562
Epoch 7/50
389/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55950397440.0000 - mae: 206686.5625

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55853244416.0000 - mae: 206551.1406 - val_loss: 56536084480.0000 - val_mae: 207392.7969
Epoch 8/50
393/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55909670912.0000 - mae: 206650.4688

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 55768285184.0000 - mae: 206414.4844 - val_loss: 56445374464.0000 - val_mae: 207246.3750
Epoch 9/50
397/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55865171968.0000 - mae: 206616.2656

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55676817408.0000 - mae: 206265.5781 - val_loss: 56344473600.0000 - val_mae: 207086.8906
Epoch 10/50
406/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55707676672.0000 - mae: 206340.2500

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55575756800.0000 - mae: 206100.2656 - val_loss: 56231497728.0000 - val_mae: 206906.9062
Epoch 11/50
398/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55648935936.0000 - mae: 206262.8281

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55467507712.0000 - mae: 205923.0781 - val_loss: 56129490944.0000 - val_mae: 206735.4375
Epoch 12/50
400/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55536726016.0000 - mae: 206088.5938

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55349534720.0000 - mae: 205728.9531 - val_loss: 55997001728.0000 - val_mae: 206515.1719
Epoch 13/50
406/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55361572864.0000 - mae: 205772.5781

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 55229829120.0000 - mae: 205532.2500 - val_loss: 55850381312.0000 - val_mae: 206275.0625
Epoch 14/50
411/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55101014016.0000 - mae: 205345.9219

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55097946112.0000 - mae: 205315.0000 - val_loss: 55759192064.0000 - val_mae: 206137.0469
Epoch 15/50
403/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55136903168.0000 - mae: 205413.7812

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54960091136.0000 - mae: 205088.0938 - val_loss: 55598112768.0000 - val_mae: 205867.2031
Epoch 16/50
388/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54909390848.0000 - mae: 204951.6250

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54819336192.0000 - mae: 204852.6250 - val_loss: 55473037312.0000 - val_mae: 205656.8750
Epoch 17/50
399/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54838943744.0000 - mae: 204922.2812

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54666027008.0000 - mae: 204600.0312 - val_loss: 55278202880.0000 - val_mae: 205342.5312
Epoch 18/50
393/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54649278464.0000 - mae: 204572.9062

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54507487232.0000 - mae: 204334.1406 - val_loss: 55148593152.0000 - val_mae: 205119.5469
Epoch 19/50
407/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54465658880.0000 - mae: 204293.8125

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 54347333632.0000 - mae: 204063.8594 - val_loss: 54945443840.0000 - val_mae: 204773.2969
Epoch 20/50
405/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54337462272.0000 - mae: 204065.6406

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 54179942400.0000 - mae: 203783.5469 - val_loss: 54787133440.0000 - val_mae: 204525.0469
Epoch 21/50
398/413 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 54179237888.0000 - mae: 203820.8281

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53998239744.0000 - mae: 203478.5469 - val_loss: 54602661888.0000 - val_mae: 204202.1250
Epoch 22/50
392/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53922529280.0000 - mae: 203345.4688

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53813460992.0000 - mae: 203169.6094 - val_loss: 54442176512.0000 - val_mae: 203937.1094
Epoch 23/50
392/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53737848832.0000 - mae: 203031.7812

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53629042688.0000 - mae: 202856.0312 - val_loss: 54242893824.0000 - val_mae: 203623.9688
Epoch 24/50
404/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 53565394944.0000 - mae: 202760.3750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 53431930880.0000 - mae: 202519.7656 - val_loss: 54017306624.0000 - val_mae: 203227.9844
Epoch 25/50
404/413 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 53357060096.0000 - mae: 202417.5469

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 53224140800.0000 - mae: 202177.0469 - val_loss: 53821825024.0000 - val_mae: 202883.5000
Epoch 26/50
410/413 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53047418880.0000 - mae: 201871.9688

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 53025304576.0000 - mae: 201829.6875 - val_loss: 53602316288.0000 - val_mae: 202529.3125
Epoch 27/50
396/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52948717568.0000 - mae: 201730.6875

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 52801175552.0000 - mae: 201448.5625 - val_loss: 53409787904.0000 - val_mae: 202212.5312
Epoch 28/50
407/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52708405248.0000 - mae: 201322.6875

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 52591333376.0000 - mae: 201090.9531 - val_loss: 53174087680.0000 - val_mae: 201820.0156
Epoch 29/50
404/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52490493952.0000 - mae: 200932.2344

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 52358377472.0000 - mae: 200691.7188 - val_loss: 53001252864.0000 - val_mae: 201491.8438
Epoch 30/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 52130041856.0000 - mae: 200293.7812

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 52130041856.0000 - mae: 200293.7812 - val_loss: 52704514048.0000 - val_mae: 200989.2969
Epoch 31/50
409/413 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51964399616.0000 - mae: 200017.4219

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 51896414208.0000 - mae: 199890.5000 - val_loss: 52472483840.0000 - val_mae: 200592.7656
Epoch 32/50
409/413 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 51724054528.0000 - mae: 199595.4375

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 51656634368.0000 - mae: 199469.2031 - val_loss: 52212183040.0000 - val_mae: 200121.2344
Epoch 33/50
405/413 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51558383616.0000 - mae: 199318.4062

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 51406147584.0000 - mae: 199036.3906 - val_loss: 52032487424.0000 - val_mae: 199827.1094
Epoch 34/50
398/413 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 51341910016.0000 - mae: 198963.3438

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 51165253632.0000 - mae: 198620.7656 - val_loss: 51681640448.0000 - val_mae: 199210.1562
Epoch 35/50
385/413 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51032281088.0000 - mae: 198335.7656

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 50892398592.0000 - mae: 198145.5625 - val_loss: 51470254080.0000 - val_mae: 198833.0469
Epoch 36/50
383/413 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50833481728.0000 - mae: 197988.5781

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50642489344.0000 - mae: 197695.8281 - val_loss: 51133513728.0000 - val_mae: 198249.3125
Epoch 37/50
390/413 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50442813440.0000 - mae: 197313.2969

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50357219328.0000 - mae: 197198.7656 - val_loss: 50910855168.0000 - val_mae: 197907.1406
Epoch 38/50
374/413 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50453946368.0000 - mae: 197391.5156

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50078580736.0000 - mae: 196709.5781 - val_loss: 50720219136.0000 - val_mae: 197627.6094
Epoch 39/50
404/413 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49927843840.0000 - mae: 196455.0938

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49798426624.0000 - mae: 196212.3594 - val_loss: 50301902848.0000 - val_mae: 196768.6719
Epoch 40/50
383/413 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49725882368.0000 - mae: 196036.8438

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49534754816.0000 - mae: 195737.9531 - val_loss: 50038673408.0000 - val_mae: 196309.6562
Epoch 41/50
408/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49291096064.0000 - mae: 195340.7188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49215836160.0000 - mae: 195178.0469 - val_loss: 49787723776.0000 - val_mae: 195829.0312
Epoch 42/50
402/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49106116608.0000 - mae: 195014.0312

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48925659136.0000 - mae: 194656.9062 - val_loss: 49309507584.0000 - val_mae: 194976.2188
Epoch 43/50
404/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 48752824320.0000 - mae: 194356.5781

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48625737728.0000 - mae: 194115.9219 - val_loss: 49133678592.0000 - val_mae: 194702.7188
Epoch 44/50
406/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 48437678080.0000 - mae: 193792.4531

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48311443456.0000 - mae: 193545.8281 - val_loss: 48813842432.0000 - val_mae: 194087.9688
Epoch 45/50
402/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 48201875456.0000 - mae: 193378.9844

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48023465984.0000 - mae: 193022.6562 - val_loss: 48520368128.0000 - val_mae: 193543.4062
Epoch 46/50
411/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 47716089856.0000 - mae: 192473.0156

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 47712296960.0000 - mae: 192441.6719 - val_loss: 48263839744.0000 - val_mae: 193089.5156
Epoch 47/50
381/413 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 47632855040.0000 - mae: 192260.2188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 47389937664.0000 - mae: 191859.4844 - val_loss: 47831011328.0000 - val_mae: 192405.8594
Epoch 48/50
380/413 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 47298658304.0000 - mae: 191654.6719

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 47063142400.0000 - mae: 191261.5781 - val_loss: 47519911936.0000 - val_mae: 191815.3281
Epoch 49/50
406/413 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 46853705728.0000 - mae: 190882.6250

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 46730182656.0000 - mae: 190636.3750 - val_loss: 47195860992.0000 - val_mae: 191038.7812
Epoch 50/50
410/413 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 46423830528.0000 - mae: 190073.4844

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 46400585728.0000 - mae: 190029.1562 - val_loss: 46827581440.0000 - val_mae: 190519.5781
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

2026/10/18 18:38:23 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/10/18 18:38:23 INFO mlflow.utils.uv_utils: Detected uv project: found uv.lock and pyproject.toml in c:\syed_taha\ds-october-2026\week2
2026/10/18 18:38:23 INFO mlflow.utils.environment: Detected uv project at c:\syed_taha\ds-october-2026\week2. Attempting to export requirements via 'uv export'.
2026/10/18 18:38:23 INFO mlflow.utils.uv_utils: Exported 141 dependencies via uv
2026/10/18 18:38:23 INFO mlflow.utils.environment: Successfully exported 141 requirements from uv project. Skipping package capture based inference.
2026/10/18 18:38:23 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

All three models have successfully run and been logged in MLflow!