In [130]:
import pandas as pd

In [131]:
df_housing=pd.read_csv("housing.csv")

In [132]:
df_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [133]:
df_housing.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [134]:
df_housing.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [135]:
median=df_housing['total_bedrooms'].median()

In [136]:
df_housing['total_bedrooms']=df_housing['total_bedrooms'].fillna(median)

In [137]:
df_housing['total_bedrooms'].isnull().sum()

np.int64(0)

In [138]:
df_housing=pd.get_dummies(df_housing,columns=['ocean_proximity'])

In [139]:
df_housing.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
20635    False
20636    False
20637    False
20638    False
20639    False
Length: 20640, dtype: bool

In [140]:
df_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,False,False,False,True,False
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,False,False,False,True,False
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,False,False,False,True,False
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,False,False,False,True,False
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,False,True,False,False,False
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,False,True,False,False,False
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,False,True,False,False,False
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,False,True,False,False,False
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,False,True,False,False,False

In [141]:
ocean_cols = [
    'ocean_proximity_<1H OCEAN',
    'ocean_proximity_INLAND',
    'ocean_proximity_ISLAND',
    'ocean_proximity_NEAR BAY',
    'ocean_proximity_NEAR OCEAN'
]

df_housing[ocean_cols]=df_housing[ocean_cols].astype(int)

In [142]:
df_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,0,0,0,1,0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,0,0,0,1,0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,0,0,0,1,0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,0,0,0,1,0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,0,1,0,0,0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,0,1,0,0,0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,0,1,0,0,0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,0,1,0,0,0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,0,1,0,0,0

In [143]:
df_housing.dtypes

longitude                     float64
latitude                      float64
housing_median_age            float64
total_rooms                   float64
total_bedrooms                float64
population                    float64
households                    float64
median_income                 float64
median_house_value            float64
ocean_proximity_<1H OCEAN       int64
ocean_proximity_INLAND          int64
ocean_proximity_ISLAND          int64
ocean_proximity_NEAR BAY        int64
ocean_proximity_NEAR OCEAN      int64
dtype: object

In [144]:
from sklearn.model_selection import train_test_split

features=['longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income']+ocean_cols

X=df_housing[features]
y=df_housing['median_house_value']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

print(X_train.shape)
print(X_test.shape)

(16512, 13)
(4128, 13)

In [145]:
print(X_test.head(2))
print(y_test.head(2))

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
20046    -119.01     36.06                25.0       1505.0           435.0
3024     -119.46     35.14                30.0       2943.0           435.0

       population  households  median_income  ocean_proximity_<1H OCEAN  \
20046      1392.0       359.0         1.6812                          0
3024       1565.0       584.0         2.5313                          0

       ocean_proximity_INLAND  ocean_proximity_ISLAND  \
20046                       1                       0
3024                        1                       0

       ocean_proximity_NEAR BAY  ocean_proximity_NEAR OCEAN
20046                         0                           0
3024                          0                           0
20046    47700.0
3024     45800.0
Name: median_house_value, dtype: float64

In [146]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)    
X_test = scaler.transform(X_test)

BASE LINE with 30 Epochs and batch size is 30

In [147]:
#from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import Dense, Input

# Model 1: Baseline MLP (Modern & Clean Way)
#model_baseline = Sequential([
 #   Input(shape=(X_train.shape[1],)),  # Yeh pehli line mein input define kar diya
  #  Dense(64, activation='relu'),
   # Dense(32, activation='relu'),
    #Dense(1)  # Regression ke liye 1 output
#])

#model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
#history_baseline = model_baseline.fit(X_train, y_train, validation_split=0.2, epochs=30, batch_size=30, verbose=1)

In [148]:
#import matplotlib.pyplot as plt

#h = history_baseline.history

#plt.figure(figsize=(12, 4))

# 1. Loss (MSE)
#plt.subplot(1, 2, 1)
#plt.plot(h['loss'], label='Train loss')
#plt.plot(h['val_loss'], label='Validation loss')
#plt.title('Baseline MLP: Loss (MSE)')
#plt.xlabel('Epoch')
#plt.ylabel('Loss')
#plt.legend()

# 2. MAE
#plt.subplot(1, 2, 2)
#plt.plot(h['mae'], label='Train MAE')
#plt.plot(h['val_mae'], label='Validation MAE')
#plt.title('Baseline MLP: MAE')
#plt.xlabel('Epoch')
#plt.ylabel('MAE ($)')
#plt.legend()

#plt.tight_layout()
#plt.show()

BASE LINE WITH 50 EPOCHS AND BATCH SIZE IS 50

In [149]:
#from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import Dense, Input

# Model 1: Baseline MLP (Modern & Clean Way)
#model_baseline = Sequential([
 #   Input(shape=(X_train.shape[1],)),  # Yeh pehli line mein input define kar diya
  #  Dense(64, activation='relu'),
   # Dense(32, activation='relu'),
    #Dense(1)  # Regression ke liye 1 output
#])

#model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
#history_baseline = model_baseline.fit(X_train, y_train, validation_split=0.2, epochs=50, batch_size=50, verbose=1)

2) Deeper DNN (MULTIPLE LAYERS)

In [150]:
#from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import Dense, Input

# Model 1: Baseline MLP (Modern & Clean Way)
#model_baseline = Sequential([
 #   Input(shape=(X_train.shape[1],)),  # Yeh pehli line mein input define kar diya
  #  Dense(128, activation='relu'),
   # Dense(64, activation='relu'),
    #Dense(32, activation='relu'),
    #Dense(16, activation='relu'),
    #Dense(1)  # Regression ke liye 1 output
#])

#model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
#history_baseline = model_baseline.fit(X_train, y_train, validation_split=0.2, epochs=50, batch_size=50, verbose=1)

now with 75 epochs with 75 batch size

In [151]:
#from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import Dense, Input

# Model 1: Baseline MLP (Modern & Clean Way)
#model_baseline = Sequential([
 #   Input(shape=(X_train.shape[1],)),  # Yeh pehli line mein input define kar diya
  #  Dense(128, activation='relu'),
   # Dense(64, activation='relu'),
    #Dense(32, activation='relu'),
    #Dense(16, activation='relu'),
    #Dense(1)  # Regression ke liye 1 output
#])

#model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
#history_baseline = model_baseline.fit(X_train, y_train, validation_split=0.2, epochs=75, batch_size=75, verbose=1)

3)Regularised DNN

In [152]:
#from tensorflow.keras.layers import Dropout, BatchNormalization
#from tensorflow.keras.callbacks import EarlyStopping

# Model 3: Regularised DNN
#model_regularised = Sequential([
 #   Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
  #  BatchNormalization(),
   # Dropout(0.1), # 30% neurons drop kar dega taake overfit na ho
    #Dense(32, activation='relu'),
    #BatchNormalization(),
    #Dropout(0.2),
    #Dense(1)
#])

#model_regularised.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# Early stopping callback
#early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

#history_reg = model_regularised.fit(
 #   X_train, y_train, 
  #  validation_split=0.2, 
   # epochs=50, 
    #batch_size=32, 
    #callbacks=[early_stop],
    #verbose=1
#)

In [153]:
# import mlflow
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, Input
# from tensorflow.keras.callbacks import EarlyStopping

# # 1. MLflow Experiment Set karein
# mlflow.set_experiment("w2-syed-taha")
# mlflow.autolog()

# # ==========================================
# # 1. BASELINE MLP
# # ==========================================
# with mlflow.start_run(run_name="mlp-baseline"):
#     model_baseline = Sequential([
#         Input(shape=(X_train.shape[1],)),
#         Dense(64, activation='relu'),
#         Dense(32, activation='relu'),
#         Dense(1)
#     ])
#     model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    
#     history_baseline = model_baseline.fit(
#         X_train, y_train, 
#         validation_split=0.2, 
#         epochs=30, 
#         batch_size=30,
#         verbose=1
#     )
#     mlflow.log_param("model_type", "Baseline MLP")

# # ==========================================
# # 1b. BASELINE MLP - 50 EPOCHS
# # ==========================================
# with mlflow.start_run(run_name="mlp-baseline-50ep"):
#     model_baseline_50 = Sequential([
#         Input(shape=(X_train.shape[1],)),
#         Dense(64, activation='relu'),
#         Dense(32, activation='relu'),
#         Dense(1)
#     ])
#     model_baseline_50.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

#     history_baseline_50 = model_baseline_50.fit(
#         X_train, y_train,
#         validation_split=0.2,
#         epochs=50,        # changed from 30
#         batch_size=30,    # same as before
#         verbose=1
#     )
#     mlflow.log_param("model_type", "Baseline MLP 50 epochs")
# # ==========================================
# # 2. DEEPER DNN
# # ==========================================
# with mlflow.start_run(run_name="mlp-deeper"):
#     model_deeper = Sequential([
#         Input(shape=(X_train.shape[1],)),
#         Dense(128, activation='relu'),
#         Dense(64, activation='relu'),
#         Dense(32, activation='relu'),
#         Dense(16, activation='relu'),
#         Dense(1)
#     ])
#     model_deeper.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    
#     history_deeper = model_deeper.fit(
#         X_train, y_train, 
#         validation_split=0.2, 
#         epochs=50, 
#         batch_size=50, 
#         verbose=1
#     )
#     mlflow.log_param("model_type", "Deeper DNN")


# # ==========================================
# # 3. REGULARISED DNN
# # ==========================================
# with mlflow.start_run(run_name="mlp-regularised"):
#     model_regularised = Sequential([
#         Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
#         BatchNormalization(),
#         Dropout(0.1),
#         Dense(32, activation='relu'),
#         BatchNormalization(),
#         Dropout(0.2),
#         Dense(1)
#     ])
#     model_regularised.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    
#     early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
    
#     history_reg = model_regularised.fit(
#         X_train, y_train, 
#         validation_split=0.2, 
#         epochs=50, 
#         batch_size=32, 
#         callbacks=[early_stop],
#         verbose=1
#     )
#     mlflow.log_param("model_type", "Regularised DNN")

# print("All three models have successfully run and been logged in MLflow!")

In [154]:
import mlflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, Input

mlflow.set_experiment("w2-syed-taha")
mlflow.autolog()

2026/10/25 01:44:48 WARNING mlflow.utils.autologging_utils: MLflow keras autologging is known to be compatible with 3.7.0 <= keras, but the installed version is 3.16.0.dev2026101803. If you encounter errors during autologging, try upgrading / downgrading keras to a compatible version, or try upgrading MLflow.
2026/10/25 01:44:48 INFO mlflow.tracking.fluent: Autologging successfully enabled for keras.
2026/10/25 01:44:49 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2026/10/25 01:44:49 WARNING mlflow.utils.autologging_utils: MLflow tensorflow autologging is known to be compatible with 2.17.1 <= tensorflow, but the installed version is 2.22.0-rc0. If you encounter errors during autologging, try upgrading / downgrading tensorflow to a compatible version, or try upgrading MLflow.
2026/10/25 01:44:49 INFO mlflow.tracking.fluent: Autologging successfully enabled for tensorflow.

In [155]:
# --- Baseline, 30 epochs ---
with mlflow.start_run(run_name="mlp-baseline-30ep"):
    model = Sequential([
        Input(shape=(X_train.shape[1],)),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(1)
    ])
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    model.fit(X_train, y_train, validation_split=0.2,
              epochs=30, batch_size=30, verbose=1)
    mlflow.log_param("model_type", "Baseline MLP 30 epochs")

# --- Baseline, 50 epochs ---
with mlflow.start_run(run_name="mlp-baseline-50ep"):
    model = Sequential([
        Input(shape=(X_train.shape[1],)),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(1)
    ])
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    model.fit(X_train, y_train, validation_split=0.2,
              epochs=50, batch_size=30, verbose=1)
    mlflow.log_param("model_type", "Baseline MLP 50 epochs")

2026/10/25 01:44:49 WARNING mlflow.tensorflow: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'

Epoch 1/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 55978827776.0000 - mae: 206651.4219

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 55978827776.0000 - mae: 206651.4219 - val_loss: 56127422464.0000 - val_mae: 206391.8594
Epoch 2/30
435/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 53509685248.0000 - mae: 201547.0781

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 53392551936.0000 - mae: 201301.6094 - val_loss: 51022520320.0000 - val_mae: 195800.0312
Epoch 3/30
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 45729595392.0000 - mae: 184509.6250

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 45500084224.0000 - mae: 184000.6562 - val_loss: 40303591424.0000 - val_mae: 171296.2188
Epoch 4/30
429/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 33606957056.0000 - mae: 153999.9688

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 33328070656.0000 - mae: 153241.2500 - val_loss: 27253035008.0000 - val_mae: 135436.2812
Epoch 5/30
430/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21628694528.0000 - mae: 117618.2500

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 21436844032.0000 - mae: 116949.4219 - val_loss: 17125831680.0000 - val_mae: 101558.6641
Epoch 6/30
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13977359360.0000 - mae: 91289.2188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 13944275968.0000 - mae: 91146.7500 - val_loss: 12190050304.0000 - val_mae: 83723.9922
Epoch 7/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10823881728.0000 - mae: 79827.5000

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 10823881728.0000 - mae: 79827.5000 - val_loss: 10413857792.0000 - val_mae: 76763.4844
Epoch 8/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9626368000.0000 - mae: 74688.6094

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9626368000.0000 - mae: 74688.6094 - val_loss: 9560422400.0000 - val_mae: 72992.3203
Epoch 9/30
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8947661824.0000 - mae: 71259.6094

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8926089216.0000 - mae: 71173.2266 - val_loss: 8933761024.0000 - val_mae: 70070.1172
Epoch 10/30
429/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8427825152.0000 - mae: 68502.6328

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8375124480.0000 - mae: 68267.5938 - val_loss: 8404519424.0000 - val_mae: 67544.5234
Epoch 11/30
428/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7939726848.0000 - mae: 65976.7969

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7904353280.0000 - mae: 65803.8906 - val_loss: 7942086656.0000 - val_mae: 65297.6289
Epoch 12/30
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7495471104.0000 - mae: 63651.3086

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 7490296832.0000 - mae: 63629.5898 - val_loss: 7533062144.0000 - val_mae: 63238.2734
Epoch 13/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7121116160.0000 - mae: 61675.6992

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7121116160.0000 - mae: 61675.6992 - val_loss: 7169243136.0000 - val_mae: 61354.1758
Epoch 14/30
429/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6832907776.0000 - mae: 60093.6523

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6790512640.0000 - mae: 59907.7695 - val_loss: 6845755392.0000 - val_mae: 59629.8164
Epoch 15/30
434/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6511681536.0000 - mae: 58386.9609

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6495636480.0000 - mae: 58313.4883 - val_loss: 6559616000.0000 - val_mae: 58074.0430
Epoch 16/30
434/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6248194560.0000 - mae: 56949.8164

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6233469952.0000 - mae: 56879.2695 - val_loss: 6307553792.0000 - val_mae: 56724.4922
Epoch 17/30
434/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6014591488.0000 - mae: 55671.8945

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6001073152.0000 - mae: 55605.6523 - val_loss: 6086673408.0000 - val_mae: 55563.3008
Epoch 18/30
429/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5830285824.0000 - mae: 54653.1562

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5796512256.0000 - mae: 54497.1055 - val_loss: 5894579200.0000 - val_mae: 54537.8906
Epoch 19/30
440/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5619872768.0000 - mae: 53556.1445

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5617585152.0000 - mae: 53546.5273 - val_loss: 5728578560.0000 - val_mae: 53648.7812
Epoch 20/30
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5471723008.0000 - mae: 52780.6914

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5461689856.0000 - mae: 52736.8281 - val_loss: 5586422272.0000 - val_mae: 52919.0156
Epoch 21/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5327240192.0000 - mae: 52053.8281

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5327240192.0000 - mae: 52053.8281 - val_loss: 5466607104.0000 - val_mae: 52322.0547
Epoch 22/30
430/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5235058688.0000 - mae: 51601.4453

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5212489728.0000 - mae: 51490.4883 - val_loss: 5365514240.0000 - val_mae: 51831.8242
Epoch 23/30
439/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5111825920.0000 - mae: 51015.9023

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5114767872.0000 - mae: 51021.1680 - val_loss: 5279833600.0000 - val_mae: 51409.9531
Epoch 24/30
427/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5045231616.0000 - mae: 50696.5391

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5031792640.0000 - mae: 50628.1523 - val_loss: 5208269824.0000 - val_mae: 51053.4609
Epoch 25/30
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4962089472.0000 - mae: 50298.7148

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4961596928.0000 - mae: 50300.3750 - val_loss: 5147848704.0000 - val_mae: 50768.7031
Epoch 26/30
433/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4912187392.0000 - mae: 50064.5391

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4901913088.0000 - mae: 50021.2734 - val_loss: 5096526848.0000 - val_mae: 50529.7070
Epoch 27/30
431/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4864515584.0000 - mae: 49849.7188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4850242048.0000 - mae: 49776.9805 - val_loss: 5051959808.0000 - val_mae: 50317.1172
Epoch 28/30
439/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4802218496.0000 - mae: 49549.5977

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4805076992.0000 - mae: 49558.2500 - val_loss: 5013351424.0000 - val_mae: 50130.7188
Epoch 29/30
431/441 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4779475968.0000 - mae: 49438.8711

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4765351936.0000 - mae: 49362.9414 - val_loss: 4979389440.0000 - val_mae: 49964.7578
Epoch 30/30
431/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4744285696.0000 - mae: 49264.7188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4730221568.0000 - mae: 49187.1016 - val_loss: 4949495296.0000 - val_mae: 49817.2188
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step

2026/10/25 01:46:01 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/10/25 01:46:01 INFO mlflow.utils.uv_utils: Detected uv project: found uv.lock and pyproject.toml in c:\syed_taha\ds-october-2026\week2
2026/10/25 01:46:01 INFO mlflow.utils.environment: Detected uv project at c:\syed_taha\ds-october-2026\week2. Attempting to export requirements via 'uv export'.
2026/10/25 01:46:01 INFO mlflow.utils.uv_utils: Exported 151 dependencies via uv
2026/10/25 01:46:01 INFO mlflow.utils.environment: Successfully exported 151 requirements from uv project. Skipping package capture based inference.
2026/10/25 01:46:02 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/10/25 01:46:03 WARNING mlflow.tensorflow: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'

Epoch 1/50
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 55962324992.0000 - mae: 206616.1250

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 55962324992.0000 - mae: 206616.1250 - val_loss: 56055181312.0000 - val_mae: 206239.0938
Epoch 2/50
427/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 53384593408.0000 - mae: 201243.3750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 53113184256.0000 - mae: 200695.9375 - val_loss: 50430951424.0000 - val_mae: 194475.6719
Epoch 3/50
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 44728410112.0000 - mae: 182115.5781

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 44495818752.0000 - mae: 181585.0312 - val_loss: 38861254656.0000 - val_mae: 167566.4219
Epoch 4/50
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31744743424.0000 - mae: 148593.2188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 31636430848.0000 - mae: 148271.4531 - val_loss: 25435996160.0000 - val_mae: 129407.9844
Epoch 5/50
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19875710976.0000 - mae: 111137.1250

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 19802353664.0000 - mae: 110860.7031 - val_loss: 15779792896.0000 - val_mae: 95758.7578
Epoch 6/50
435/441 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12977015808.0000 - mae: 87078.5547

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 12936072192.0000 - mae: 86887.5312 - val_loss: 11465978880.0000 - val_mae: 80258.6719
Epoch 7/50
433/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10308837376.0000 - mae: 77463.1172

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 10269911040.0000 - mae: 77292.4531 - val_loss: 9933058048.0000 - val_mae: 74368.5703
Epoch 8/50
434/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9240639488.0000 - mae: 72832.9141

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9213276160.0000 - mae: 72711.3750 - val_loss: 9132241920.0000 - val_mae: 70990.9219
Epoch 9/50
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8577172992.0000 - mae: 69463.7188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8549970432.0000 - mae: 69330.6094 - val_loss: 8525346304.0000 - val_mae: 68184.0156
Epoch 10/50
431/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8046970368.0000 - mae: 66640.9062

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 8016179200.0000 - mae: 66497.8203 - val_loss: 8013840896.0000 - val_mae: 65695.3281
Epoch 11/50
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7563074048.0000 - mae: 64078.2109

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7557670912.0000 - mae: 64054.0195 - val_loss: 7569422848.0000 - val_mae: 63453.0820
Epoch 12/50
439/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7153319424.0000 - mae: 61892.3945

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7154938368.0000 - mae: 61895.3438 - val_loss: 7178941952.0000 - val_mae: 61422.2031
Epoch 13/50
426/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6831785472.0000 - mae: 60108.3750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6799432192.0000 - mae: 59953.4297 - val_loss: 6836398592.0000 - val_mae: 59571.0469
Epoch 14/50
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6486153728.0000 - mae: 58214.9648

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6486153728.0000 - mae: 58214.9648 - val_loss: 6538253312.0000 - val_mae: 57921.0664
Epoch 15/50
428/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6234111488.0000 - mae: 56789.8750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6210466304.0000 - mae: 56673.4688 - val_loss: 6278409728.0000 - val_mae: 56465.6797
Epoch 16/50
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5982253056.0000 - mae: 55405.8633

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5969646080.0000 - mae: 55346.1797 - val_loss: 6055461888.0000 - val_mae: 55241.6211
Epoch 17/50
426/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5786763264.0000 - mae: 54356.4023

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5761338880.0000 - mae: 54234.2227 - val_loss: 5864534016.0000 - val_mae: 54246.9414
Epoch 18/50
418/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5605163008.0000 - mae: 53407.6172

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 5582585856.0000 - mae: 53306.7930 - val_loss: 5701059072.0000 - val_mae: 53413.2617
Epoch 19/50
399/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5458150400.0000 - mae: 52604.3359

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 5429022720.0000 - mae: 52536.0781 - val_loss: 5561607680.0000 - val_mae: 52710.9688
Epoch 20/50
407/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5309490688.0000 - mae: 51930.6289

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 5297982976.0000 - mae: 51903.3477 - val_loss: 5444035072.0000 - val_mae: 52147.6680
Epoch 21/50
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5196322816.0000 - mae: 51425.4766

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 5187311104.0000 - mae: 51387.7656 - val_loss: 5346052096.0000 - val_mae: 51698.8906
Epoch 22/50
415/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5110842880.0000 - mae: 50993.4453

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 5094607360.0000 - mae: 50963.2500 - val_loss: 5265845760.0000 - val_mae: 51332.8555
Epoch 23/50
405/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5034964480.0000 - mae: 50674.0000

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 5016957440.0000 - mae: 50607.0078 - val_loss: 5198489600.0000 - val_mae: 51021.8438
Epoch 24/50
421/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4972139008.0000 - mae: 50401.6406

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4950886912.0000 - mae: 50299.5000 - val_loss: 5141096448.0000 - val_mae: 50762.3086
Epoch 25/50
408/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4900022272.0000 - mae: 50060.1406

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4893635072.0000 - mae: 50027.4180 - val_loss: 5092082176.0000 - val_mae: 50529.9922
Epoch 26/50
414/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4863180288.0000 - mae: 49854.6289

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4843559424.0000 - mae: 49784.9180 - val_loss: 5049682432.0000 - val_mae: 50316.0508
Epoch 27/50
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4807198720.0000 - mae: 49598.2617

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4799545856.0000 - mae: 49565.6797 - val_loss: 5013049344.0000 - val_mae: 50128.2812
Epoch 28/50
424/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4775270400.0000 - mae: 49462.7539

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4760801792.0000 - mae: 49370.2578 - val_loss: 4980928512.0000 - val_mae: 49960.0508
Epoch 29/50
396/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4754295296.0000 - mae: 49309.8867

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4726307328.0000 - mae: 49192.7148 - val_loss: 4952051200.0000 - val_mae: 49805.7188
Epoch 30/50
416/441 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - loss: 4706191872.0000 - mae: 49081.1641

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4695289856.0000 - mae: 49030.0703 - val_loss: 4926097920.0000 - val_mae: 49663.5234
Epoch 31/50
410/441 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - loss: 4677576192.0000 - mae: 48930.7734

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4667200000.0000 - mae: 48879.9180 - val_loss: 4902651392.0000 - val_mae: 49539.7930
Epoch 32/50
440/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4642976768.0000 - mae: 48747.0703

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4641487360.0000 - mae: 48741.8750 - val_loss: 4881355776.0000 - val_mae: 49430.0469
Epoch 33/50
422/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4633992192.0000 - mae: 48718.1406

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4617927680.0000 - mae: 48615.0117 - val_loss: 4861734912.0000 - val_mae: 49331.0742
Epoch 34/50
405/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4607255552.0000 - mae: 48580.7891

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4596262912.0000 - mae: 48496.6992 - val_loss: 4843409408.0000 - val_mae: 49241.4883
Epoch 35/50
429/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4600209408.0000 - mae: 48516.2930

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4576370688.0000 - mae: 48386.3008 - val_loss: 4826386944.0000 - val_mae: 49159.8672
Epoch 36/50
431/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4571338752.0000 - mae: 48362.2227

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4558042624.0000 - mae: 48282.5234 - val_loss: 4810586624.0000 - val_mae: 49082.4688
Epoch 37/50
413/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4547688448.0000 - mae: 48227.8906

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4540930048.0000 - mae: 48184.3750 - val_loss: 4795803648.0000 - val_mae: 49011.3438
Epoch 38/50
399/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4536950784.0000 - mae: 48165.8906

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4524912640.0000 - mae: 48092.2578 - val_loss: 4781966848.0000 - val_mae: 48944.8633
Epoch 39/50
440/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4511177216.0000 - mae: 48009.0820

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4509861376.0000 - mae: 48004.1875 - val_loss: 4768945152.0000 - val_mae: 48880.3711
Epoch 40/50
404/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4504488448.0000 - mae: 47995.5312

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4495704064.0000 - mae: 47921.2461 - val_loss: 4756567040.0000 - val_mae: 48820.5586
Epoch 41/50
428/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4492681216.0000 - mae: 47921.9883

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4482369024.0000 - mae: 47840.8008 - val_loss: 4744815104.0000 - val_mae: 48762.0469
Epoch 42/50
412/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4480592384.0000 - mae: 47833.2695

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4469754368.0000 - mae: 47762.9297 - val_loss: 4733649408.0000 - val_mae: 48705.7500
Epoch 43/50
421/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4473184256.0000 - mae: 47795.4648

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4457815552.0000 - mae: 47688.0000 - val_loss: 4722924544.0000 - val_mae: 48650.7617
Epoch 44/50
420/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4465926656.0000 - mae: 47751.8359

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4446443008.0000 - mae: 47615.6016 - val_loss: 4712695296.0000 - val_mae: 48598.3008
Epoch 45/50
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4449166336.0000 - mae: 47619.5000

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4435587072.0000 - mae: 47546.7578 - val_loss: 4702957568.0000 - val_mae: 48548.7969
Epoch 46/50
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4431605760.0000 - mae: 47505.7227

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4425247744.0000 - mae: 47479.6914 - val_loss: 4693643264.0000 - val_mae: 48499.6367
Epoch 47/50
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4421510144.0000 - mae: 47441.7617

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4415374848.0000 - mae: 47414.5312 - val_loss: 4684696064.0000 - val_mae: 48452.1016
Epoch 48/50
424/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4414487040.0000 - mae: 47432.6328

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4406003712.0000 - mae: 47352.7227 - val_loss: 4676231680.0000 - val_mae: 48407.1367
Epoch 49/50
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4397082112.0000 - mae: 47293.6758

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4397082112.0000 - mae: 47293.6758 - val_loss: 4668155392.0000 - val_mae: 48363.8047
Epoch 50/50
411/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4398347776.0000 - mae: 47293.0586

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4388561408.0000 - mae: 47236.9922 - val_loss: 4660401152.0000 - val_mae: 48321.8516
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

2026/10/25 01:47:09 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/10/25 01:47:09 INFO mlflow.utils.uv_utils: Detected uv project: found uv.lock and pyproject.toml in c:\syed_taha\ds-october-2026\week2
2026/10/25 01:47:09 INFO mlflow.utils.environment: Detected uv project at c:\syed_taha\ds-october-2026\week2. Attempting to export requirements via 'uv export'.
2026/10/25 01:47:09 INFO mlflow.utils.uv_utils: Exported 151 dependencies via uv
2026/10/25 01:47:09 INFO mlflow.utils.environment: Successfully exported 151 requirements from uv project. Skipping package capture based inference.
2026/10/25 01:47:09 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

In [156]:
# --- Deeper, 30 epochs ---
with mlflow.start_run(run_name="mlp-deeper-30ep"):
    model = Sequential([
        Input(shape=(X_train.shape[1],)),
        Dense(128, activation='relu'),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(16, activation='relu'),
        Dense(1)
    ])
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    model.fit(X_train, y_train, validation_split=0.2,
              epochs=30, batch_size=30, verbose=1)
    mlflow.log_param("model_type", "Deeper DNN 30 epochs")

# --- Deeper, 50 epochs ---
with mlflow.start_run(run_name="mlp-deeper-50ep"):
    model = Sequential([
        Input(shape=(X_train.shape[1],)),
        Dense(128, activation='relu'),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(16, activation='relu'),
        Dense(1)
    ])
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    model.fit(X_train, y_train, validation_split=0.2,
              epochs=50, batch_size=30, verbose=1)
    mlflow.log_param("model_type", "Deeper DNN 50 epochs")

2026/10/25 01:47:10 WARNING mlflow.tensorflow: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'

Epoch 1/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 31289110528.0000 - mae: 136568.1094

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 31289110528.0000 - mae: 136568.1094 - val_loss: 7638639104.0000 - val_mae: 63289.6484
Epoch 2/30
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6386795008.0000 - mae: 57655.8086

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6372972544.0000 - mae: 57584.8789 - val_loss: 5799135744.0000 - val_mae: 53758.0234
Epoch 3/30
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5306696704.0000 - mae: 51899.9180

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5295728128.0000 - mae: 51857.0898 - val_loss: 5208242688.0000 - val_mae: 50828.4570
Epoch 4/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4877743616.0000 - mae: 49810.1445

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4877743616.0000 - mae: 49810.1445 - val_loss: 4958428672.0000 - val_mae: 49672.9961
Epoch 5/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4665721856.0000 - mae: 48732.5977

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4665721856.0000 - mae: 48732.5977 - val_loss: 4817923072.0000 - val_mae: 49016.9102
Epoch 6/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4535102464.0000 - mae: 48035.5234

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4535102464.0000 - mae: 48035.5234 - val_loss: 4726440960.0000 - val_mae: 48596.1602
Epoch 7/30
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4454359040.0000 - mae: 47558.5312

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4448511488.0000 - mae: 47539.7695 - val_loss: 4662970880.0000 - val_mae: 48297.0977
Epoch 8/30
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4400909312.0000 - mae: 47227.7031

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 4385873408.0000 - mae: 47159.7812 - val_loss: 4614701056.0000 - val_mae: 48042.9531
Epoch 9/30
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4336791040.0000 - mae: 46831.4805

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 4336243712.0000 - mae: 46845.1250 - val_loss: 4575464448.0000 - val_mae: 47819.7812
Epoch 10/30
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4301206016.0000 - mae: 46602.2695

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 4296166400.0000 - mae: 46589.6758 - val_loss: 4544197120.0000 - val_mae: 47627.0938
Epoch 11/30
439/441 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4260699904.0000 - mae: 46356.0859

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 4263740928.0000 - mae: 46377.5977 - val_loss: 4518273536.0000 - val_mae: 47457.6602
Epoch 12/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4236367616.0000 - mae: 46195.9805

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 4236367616.0000 - mae: 46195.9805 - val_loss: 4496638464.0000 - val_mae: 47314.4414
Epoch 13/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4212943616.0000 - mae: 46040.9688

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4212943616.0000 - mae: 46040.9688 - val_loss: 4478046720.0000 - val_mae: 47186.4805
Epoch 14/30
435/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4196201472.0000 - mae: 45926.5391

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 4192422400.0000 - mae: 45906.1250 - val_loss: 4461684736.0000 - val_mae: 47072.5117
Epoch 15/30
430/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4191660032.0000 - mae: 45891.6680

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4174102272.0000 - mae: 45785.8945 - val_loss: 4446666240.0000 - val_mae: 46967.6289
Epoch 16/30
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4162398720.0000 - mae: 45684.2773

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4157632768.0000 - mae: 45677.1094 - val_loss: 4433538560.0000 - val_mae: 46876.5312
Epoch 17/30
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4147085312.0000 - mae: 45586.0039

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4143149568.0000 - mae: 45581.6484 - val_loss: 4422458368.0000 - val_mae: 46797.0703
Epoch 18/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4129924864.0000 - mae: 45493.4297

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4129924864.0000 - mae: 45493.4297 - val_loss: 4412226048.0000 - val_mae: 46720.2852
Epoch 19/30
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4117571584.0000 - mae: 45392.2109

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4117721088.0000 - mae: 45409.8047 - val_loss: 4402683392.0000 - val_mae: 46645.1680
Epoch 20/30
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4109930752.0000 - mae: 45334.9531

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 4106348288.0000 - mae: 45332.6602 - val_loss: 4393936896.0000 - val_mae: 46580.7852
Epoch 21/30
428/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4105263616.0000 - mae: 45336.4219

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4095849216.0000 - mae: 45260.0781 - val_loss: 4386100224.0000 - val_mae: 46519.7266
Epoch 22/30
440/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4085908224.0000 - mae: 45189.0000

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4085930240.0000 - mae: 45191.1992 - val_loss: 4378813440.0000 - val_mae: 46462.6328
Epoch 23/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4076835328.0000 - mae: 45125.4062

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4076835328.0000 - mae: 45125.4062 - val_loss: 4372168704.0000 - val_mae: 46408.2461
Epoch 24/30
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4067688704.0000 - mae: 45041.9375

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 4068177920.0000 - mae: 45060.9219 - val_loss: 4365566464.0000 - val_mae: 46350.9141
Epoch 25/30
431/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4071988992.0000 - mae: 45067.7148

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4060122880.0000 - mae: 44998.3125 - val_loss: 4359568384.0000 - val_mae: 46298.6523
Epoch 26/30
427/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4058105600.0000 - mae: 44996.0273

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4051965440.0000 - mae: 44937.0898 - val_loss: 4354022912.0000 - val_mae: 46250.3945
Epoch 27/30
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4047192320.0000 - mae: 44878.7070

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4044298240.0000 - mae: 44879.5781 - val_loss: 4349211136.0000 - val_mae: 46203.7812
Epoch 28/30
435/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4039580160.0000 - mae: 44841.4844

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4037087744.0000 - mae: 44824.5469 - val_loss: 4344322560.0000 - val_mae: 46155.2227
Epoch 29/30
439/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4025938432.0000 - mae: 44742.0664

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4030212608.0000 - mae: 44772.0156 - val_loss: 4339566080.0000 - val_mae: 46110.6016
Epoch 30/30
433/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4031014912.0000 - mae: 44752.9844

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 4023287552.0000 - mae: 44720.3750 - val_loss: 4335154176.0000 - val_mae: 46067.8359
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

2026/10/25 01:48:27 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/10/25 01:48:27 INFO mlflow.utils.uv_utils: Detected uv project: found uv.lock and pyproject.toml in c:\syed_taha\ds-october-2026\week2
2026/10/25 01:48:27 INFO mlflow.utils.environment: Detected uv project at c:\syed_taha\ds-october-2026\week2. Attempting to export requirements via 'uv export'.
2026/10/25 01:48:28 INFO mlflow.utils.uv_utils: Exported 151 dependencies via uv
2026/10/25 01:48:28 INFO mlflow.utils.environment: Successfully exported 151 requirements from uv project. Skipping package capture based inference.
2026/10/25 01:48:28 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/10/25 01:48:29 WARNING mlflow.tensorflow: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'

Epoch 1/50
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 36227682304.0000 - mae: 151593.2969

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 36227682304.0000 - mae: 151593.2969 - val_loss: 8843517952.0000 - val_mae: 68045.6953
Epoch 2/50
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7121632768.0000 - mae: 61046.8672

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7104471552.0000 - mae: 60957.7461 - val_loss: 6334747136.0000 - val_mae: 56242.2422
Epoch 3/50
430/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5702781952.0000 - mae: 53779.7539

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5669822464.0000 - mae: 53615.6797 - val_loss: 5465521664.0000 - val_mae: 52009.7266
Epoch 4/50
424/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5109192704.0000 - mae: 50972.5195

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 5084583936.0000 - mae: 50829.4531 - val_loss: 5109229056.0000 - val_mae: 50394.8750
Epoch 5/50
425/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4828544000.0000 - mae: 49631.4297

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4807786496.0000 - mae: 49505.8711 - val_loss: 4929247744.0000 - val_mae: 49570.0508
Epoch 6/50
421/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4671012864.0000 - mae: 48833.3984

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4649349632.0000 - mae: 48693.8789 - val_loss: 4818828800.0000 - val_mae: 49053.8008
Epoch 7/50
408/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4544991232.0000 - mae: 48180.2930

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4541969408.0000 - mae: 48096.5508 - val_loss: 4740111872.0000 - val_mae: 48685.7031
Epoch 8/50
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4478963200.0000 - mae: 47724.2188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4463933952.0000 - mae: 47649.3633 - val_loss: 4682470400.0000 - val_mae: 48432.8398
Epoch 9/50
421/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4422602752.0000 - mae: 47418.3438

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4406109184.0000 - mae: 47301.2773 - val_loss: 4638026752.0000 - val_mae: 48216.8633
Epoch 10/50
412/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4368257024.0000 - mae: 47082.4141

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4360591872.0000 - mae: 47008.8398 - val_loss: 4601703936.0000 - val_mae: 48013.7930
Epoch 11/50
422/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4335740416.0000 - mae: 46860.4141

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4322981376.0000 - mae: 46760.8008 - val_loss: 4571478016.0000 - val_mae: 47832.9531
Epoch 12/50
400/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4297460224.0000 - mae: 46672.2148

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4290785280.0000 - mae: 46547.8125 - val_loss: 4546063872.0000 - val_mae: 47668.1992
Epoch 13/50
422/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4275203584.0000 - mae: 46460.1641

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4263428352.0000 - mae: 46365.7578 - val_loss: 4524312064.0000 - val_mae: 47518.2188
Epoch 14/50
400/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4244783616.0000 - mae: 46327.7930

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4239647488.0000 - mae: 46209.8867 - val_loss: 4505217024.0000 - val_mae: 47379.3125
Epoch 15/50
431/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4231783936.0000 - mae: 46146.0312

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4218663168.0000 - mae: 46072.3047 - val_loss: 4488309760.0000 - val_mae: 47255.7930
Epoch 16/50
421/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4212547840.0000 - mae: 46049.6836

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4199551232.0000 - mae: 45948.6562 - val_loss: 4473494528.0000 - val_mae: 47147.8281
Epoch 17/50
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4196010752.0000 - mae: 45907.2500

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4182162432.0000 - mae: 45838.6016 - val_loss: 4459857408.0000 - val_mae: 47044.3516
Epoch 18/50
431/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4179415040.0000 - mae: 45811.0156

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4166522880.0000 - mae: 45738.1680 - val_loss: 4447381504.0000 - val_mae: 46949.9297
Epoch 19/50
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4156930048.0000 - mae: 45656.8672

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4152235520.0000 - mae: 45647.3242 - val_loss: 4435764224.0000 - val_mae: 46862.7656
Epoch 20/50
415/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4141904896.0000 - mae: 45582.3438

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4139060736.0000 - mae: 45563.0156 - val_loss: 4425307136.0000 - val_mae: 46787.3242
Epoch 21/50
440/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4126851840.0000 - mae: 45482.0703

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4126643968.0000 - mae: 45483.0742 - val_loss: 4415255040.0000 - val_mae: 46711.8242
Epoch 22/50
427/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4121622016.0000 - mae: 45470.6094

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4114790400.0000 - mae: 45406.5195 - val_loss: 4405470720.0000 - val_mae: 46639.4766
Epoch 23/50
430/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4120474880.0000 - mae: 45439.6523

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4103750144.0000 - mae: 45333.7930 - val_loss: 4396346880.0000 - val_mae: 46572.5039
Epoch 24/50
420/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4107132160.0000 - mae: 45376.3945

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4092748032.0000 - mae: 45258.5156 - val_loss: 4386085376.0000 - val_mae: 46494.9023
Epoch 25/50
423/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4087820544.0000 - mae: 45252.2734

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4082060032.0000 - mae: 45187.2734 - val_loss: 4377100800.0000 - val_mae: 46430.0508
Epoch 26/50
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4075729408.0000 - mae: 45125.1133

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4071927040.0000 - mae: 45119.9922 - val_loss: 4368365568.0000 - val_mae: 46363.8789
Epoch 27/50
414/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4068770304.0000 - mae: 45098.7656

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4062337280.0000 - mae: 45054.8516 - val_loss: 4360151552.0000 - val_mae: 46300.1523
Epoch 28/50
423/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4058574080.0000 - mae: 45055.0508

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4053025024.0000 - mae: 44990.3086 - val_loss: 4351806976.0000 - val_mae: 46236.5430
Epoch 29/50
431/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4055947008.0000 - mae: 44998.3789

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4044072448.0000 - mae: 44927.1758 - val_loss: 4343702016.0000 - val_mae: 46175.0859
Epoch 30/50
411/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4038052352.0000 - mae: 44908.7695

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4035268096.0000 - mae: 44866.5039 - val_loss: 4336350720.0000 - val_mae: 46118.4219
Epoch 31/50
428/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4036228608.0000 - mae: 44887.4727

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4026701312.0000 - mae: 44807.6016 - val_loss: 4329033728.0000 - val_mae: 46060.5117
Epoch 32/50
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4021733120.0000 - mae: 44751.6836

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4018529280.0000 - mae: 44750.2695 - val_loss: 4321428480.0000 - val_mae: 46003.8594
Epoch 33/50
431/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4021661184.0000 - mae: 44761.4844

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4010061056.0000 - mae: 44691.5352 - val_loss: 4314151936.0000 - val_mae: 45947.0586
Epoch 34/50
410/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4000882944.0000 - mae: 44669.9570

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4001467392.0000 - mae: 44632.5312 - val_loss: 4306822144.0000 - val_mae: 45891.4336
Epoch 35/50
439/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3988696064.0000 - mae: 44543.4570

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3993006848.0000 - mae: 44574.2617 - val_loss: 4299208192.0000 - val_mae: 45835.7852
Epoch 36/50
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3996410112.0000 - mae: 44579.6211

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 3984263936.0000 - mae: 44514.2227 - val_loss: 4291602432.0000 - val_mae: 45777.6406
Epoch 37/50
420/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3989032448.0000 - mae: 44570.5234

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3975819264.0000 - mae: 44456.5430 - val_loss: 4284180480.0000 - val_mae: 45722.9805
Epoch 38/50
430/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3982383104.0000 - mae: 44498.9609

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3967330304.0000 - mae: 44399.5586 - val_loss: 4276838656.0000 - val_mae: 45668.6055
Epoch 39/50
410/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3957777664.0000 - mae: 44376.6641

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3958756352.0000 - mae: 44341.3164 - val_loss: 4269538048.0000 - val_mae: 45612.9609
Epoch 40/50
419/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3959873536.0000 - mae: 44355.7305

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3950374912.0000 - mae: 44281.8594 - val_loss: 4262306560.0000 - val_mae: 45557.6484
Epoch 41/50
412/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3944527872.0000 - mae: 44272.6367

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3941714176.0000 - mae: 44224.2227 - val_loss: 4254933760.0000 - val_mae: 45500.4258
Epoch 42/50
422/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3941936384.0000 - mae: 44253.4727

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3933248256.0000 - mae: 44166.5234 - val_loss: 4247945472.0000 - val_mae: 45446.8867
Epoch 43/50
413/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3923097344.0000 - mae: 44127.2422

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3924689664.0000 - mae: 44107.8945 - val_loss: 4240198400.0000 - val_mae: 45390.7773
Epoch 44/50
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3915733504.0000 - mae: 44048.2500

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3915733504.0000 - mae: 44048.2500 - val_loss: 4232682240.0000 - val_mae: 45335.2617
Epoch 45/50
425/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3920165888.0000 - mae: 44082.2773

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3906875136.0000 - mae: 43988.8789 - val_loss: 4224822528.0000 - val_mae: 45277.7734
Epoch 46/50
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3899322880.0000 - mae: 43921.1172

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3897393920.0000 - mae: 43926.7773 - val_loss: 4216647168.0000 - val_mae: 45218.3477
Epoch 47/50
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3886238208.0000 - mae: 43837.3438

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3887482880.0000 - mae: 43859.0117 - val_loss: 4207694336.0000 - val_mae: 45151.7734
Epoch 48/50
421/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3887839744.0000 - mae: 43886.7773

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3876788992.0000 - mae: 43785.9570 - val_loss: 4197713920.0000 - val_mae: 45079.9453
Epoch 49/50
420/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3877815552.0000 - mae: 43823.8711

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3865033472.0000 - mae: 43708.9922 - val_loss: 4187188480.0000 - val_mae: 45006.3906
Epoch 50/50
418/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3856664320.0000 - mae: 43688.7188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3852730624.0000 - mae: 43627.2617 - val_loss: 4175553536.0000 - val_mae: 44919.3320
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

2026/10/25 01:49:25 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/10/25 01:49:25 INFO mlflow.utils.uv_utils: Detected uv project: found uv.lock and pyproject.toml in c:\syed_taha\ds-october-2026\week2
2026/10/25 01:49:25 INFO mlflow.utils.environment: Detected uv project at c:\syed_taha\ds-october-2026\week2. Attempting to export requirements via 'uv export'.
2026/10/25 01:49:25 INFO mlflow.utils.uv_utils: Exported 151 dependencies via uv
2026/10/25 01:49:25 INFO mlflow.utils.environment: Successfully exported 151 requirements from uv project. Skipping package capture based inference.
2026/10/25 01:49:25 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

In [157]:
# --- Regularised, 30 epochs ---
with mlflow.start_run(run_name="mlp-regularised-30ep"):
    model = Sequential([
        Input(shape=(X_train.shape[1],)),
        Dense(64, activation='relu'),
        BatchNormalization(),
        Dropout(0.1),
        Dense(32, activation='relu'),
        BatchNormalization(),
        Dropout(0.2),
        Dense(1)
    ])
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    model.fit(X_train, y_train, validation_split=0.2,
              epochs=30, batch_size=30, verbose=1)
    mlflow.log_param("model_type", "Regularised DNN 30 epochs")

# --- Regularised, 50 epochs ---
with mlflow.start_run(run_name="mlp-regularised-50ep"):
    model = Sequential([
        Input(shape=(X_train.shape[1],)),
        Dense(64, activation='relu'),
        BatchNormalization(),
        Dropout(0.1),
        Dense(32, activation='relu'),
        BatchNormalization(),
        Dropout(0.2),
        Dense(1)
    ])
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    model.fit(X_train, y_train, validation_split=0.2,
              epochs=50, batch_size=30, verbose=1)
    mlflow.log_param("model_type", "Regularised DNN 50 epochs")

2026/10/25 01:49:26 WARNING mlflow.tensorflow: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'

Epoch 1/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 56148914176.0000 - mae: 207010.7344

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 56148914176.0000 - mae: 207010.7344 - val_loss: 56864239616.0000 - val_mae: 207905.1094
Epoch 2/30
427/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56312643584.0000 - mae: 207323.8281

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 56128315392.0000 - mae: 206982.9531 - val_loss: 56835153920.0000 - val_mae: 207864.8906
Epoch 3/30
413/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56174940160.0000 - mae: 207005.3750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 56091631616.0000 - mae: 206928.0469 - val_loss: 56792162304.0000 - val_mae: 207799.1719
Epoch 4/30
428/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56239325184.0000 - mae: 207208.1719

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 56040894464.0000 - mae: 206849.1875 - val_loss: 56736190464.0000 - val_mae: 207714.6719
Epoch 5/30
440/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55994679296.0000 - mae: 206781.2656

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55977693184.0000 - mae: 206749.5781 - val_loss: 56667721728.0000 - val_mae: 207609.5625
Epoch 6/30
427/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56087732224.0000 - mae: 206972.4219

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55903178752.0000 - mae: 206630.3594 - val_loss: 56588197888.0000 - val_mae: 207482.2031
Epoch 7/30
428/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56017174528.0000 - mae: 206853.8750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55818788864.0000 - mae: 206494.1094 - val_loss: 56497410048.0000 - val_mae: 207340.5781
Epoch 8/30
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55804100608.0000 - mae: 206489.1719

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55723053056.0000 - mae: 206339.3750 - val_loss: 56395767808.0000 - val_mae: 207170.8125
Epoch 9/30
425/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55782199296.0000 - mae: 206488.8906

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55619002368.0000 - mae: 206170.8594 - val_loss: 56296747008.0000 - val_mae: 207017.2188
Epoch 10/30
430/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55687237632.0000 - mae: 206323.3594

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55508434944.0000 - mae: 205987.7812 - val_loss: 56181751808.0000 - val_mae: 206832.7969
Epoch 11/30
417/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55473324032.0000 - mae: 205915.0000

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55385468928.0000 - mae: 205787.0156 - val_loss: 56032903168.0000 - val_mae: 206583.6875
Epoch 12/30
424/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55411130368.0000 - mae: 205868.3125

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55256354816.0000 - mae: 205575.0938 - val_loss: 55910400000.0000 - val_mae: 206392.6875
Epoch 13/30
430/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55299170304.0000 - mae: 205686.3125

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55120867328.0000 - mae: 205350.1406 - val_loss: 55762223104.0000 - val_mae: 206144.7812
Epoch 14/30
429/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55144468480.0000 - mae: 205424.1406

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54974148608.0000 - mae: 205107.7969 - val_loss: 55618646016.0000 - val_mae: 205902.7500
Epoch 15/30
435/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54912937984.0000 - mae: 205036.4375

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54823886848.0000 - mae: 204858.2031 - val_loss: 55460753408.0000 - val_mae: 205642.0938
Epoch 16/30
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54683131904.0000 - mae: 204644.2344

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54663520256.0000 - mae: 204589.5312 - val_loss: 55304466432.0000 - val_mae: 205383.2812
Epoch 17/30
427/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54675308544.0000 - mae: 204648.0312

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54491947008.0000 - mae: 204302.8906 - val_loss: 55117283328.0000 - val_mae: 205082.4062
Epoch 18/30
435/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54405586944.0000 - mae: 204191.3750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54316670976.0000 - mae: 204012.4844 - val_loss: 54975471616.0000 - val_mae: 204861.3438
Epoch 19/30
412/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 54243385344.0000 - mae: 203811.1875

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54138322944.0000 - mae: 203709.8125 - val_loss: 54727593984.0000 - val_mae: 204429.6250
Epoch 20/30
409/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 54131507200.0000 - mae: 203672.8125

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53949165568.0000 - mae: 203394.8906 - val_loss: 54569529344.0000 - val_mae: 204191.0000
Epoch 21/30
413/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 53833125888.0000 - mae: 203138.1562

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53746184192.0000 - mae: 203050.7500 - val_loss: 54368034816.0000 - val_mae: 203828.3281
Epoch 22/30
433/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53678850048.0000 - mae: 202953.4375

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53546815488.0000 - mae: 202711.9531 - val_loss: 54195245056.0000 - val_mae: 203569.7031
Epoch 23/30
434/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53457379328.0000 - mae: 202591.5312

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53332369408.0000 - mae: 202345.5312 - val_loss: 54001328128.0000 - val_mae: 203224.0000
Epoch 24/30
430/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 53289414656.0000 - mae: 202310.7812

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 53113864192.0000 - mae: 201973.4219 - val_loss: 53727936512.0000 - val_mae: 202776.4688
Epoch 25/30
440/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 52913082368.0000 - mae: 201632.3750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 52896555008.0000 - mae: 201600.5000 - val_loss: 53485068288.0000 - val_mae: 202331.4688
Epoch 26/30
431/441 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52783616000.0000 - mae: 201419.0625

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 52652752896.0000 - mae: 201180.8438 - val_loss: 53347487744.0000 - val_mae: 202140.5781
Epoch 27/30
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 52460351488.0000 - mae: 200868.0469

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 52414910464.0000 - mae: 200776.8594 - val_loss: 52904345600.0000 - val_mae: 201287.2656
Epoch 28/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 52182020096.0000 - mae: 200371.0156

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 52182020096.0000 - mae: 200371.0156 - val_loss: 52737458176.0000 - val_mae: 201049.4219
Epoch 29/30
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 51966758912.0000 - mae: 200018.7500

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 51920744448.0000 - mae: 199926.6719 - val_loss: 52426493952.0000 - val_mae: 200520.0156
Epoch 30/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 51667148800.0000 - mae: 199486.0312

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 51667148800.0000 - mae: 199486.0312 - val_loss: 52281782272.0000 - val_mae: 200298.0469
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step

2026/10/25 01:50:09 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/10/25 01:50:09 INFO mlflow.utils.uv_utils: Detected uv project: found uv.lock and pyproject.toml in c:\syed_taha\ds-october-2026\week2
2026/10/25 01:50:09 INFO mlflow.utils.environment: Detected uv project at c:\syed_taha\ds-october-2026\week2. Attempting to export requirements via 'uv export'.
2026/10/25 01:50:09 INFO mlflow.utils.uv_utils: Exported 151 dependencies via uv
2026/10/25 01:50:09 INFO mlflow.utils.environment: Successfully exported 151 requirements from uv project. Skipping package capture based inference.
2026/10/25 01:50:10 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/10/25 01:50:11 WARNING mlflow.tensorflow: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'

Epoch 1/50
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 56148451328.0000 - mae: 207010.3750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - loss: 56148451328.0000 - mae: 207010.3750 - val_loss: 56864096256.0000 - val_mae: 207905.2656
Epoch 2/50
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 56127844352.0000 - mae: 206982.4844

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 56127844352.0000 - mae: 206982.4844 - val_loss: 56835461120.0000 - val_mae: 207865.5625
Epoch 3/50
433/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 56225288192.0000 - mae: 207167.0000

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 56091172864.0000 - mae: 206927.9062 - val_loss: 56793047040.0000 - val_mae: 207802.0469
Epoch 4/50
430/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 56219779072.0000 - mae: 207184.1875

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 56040701952.0000 - mae: 206849.5312 - val_loss: 56733540352.0000 - val_mae: 207705.7344
Epoch 5/50
433/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 56111689728.0000 - mae: 206989.0312

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 55977623552.0000 - mae: 206749.7188 - val_loss: 56667779072.0000 - val_mae: 207601.3438
Epoch 6/50
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 55922667520.0000 - mae: 206685.5781

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 55903125504.0000 - mae: 206631.2656 - val_loss: 56587280384.0000 - val_mae: 207471.2969
Epoch 7/50
434/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 55946248192.0000 - mae: 206739.7031

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 55818641408.0000 - mae: 206494.7500 - val_loss: 56499904512.0000 - val_mae: 207329.0000
Epoch 8/50
435/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 55812919296.0000 - mae: 206517.8125

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 55723651072.0000 - mae: 206340.3750 - val_loss: 56404684800.0000 - val_mae: 207168.6250
Epoch 9/50
434/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 55748272128.0000 - mae: 206417.8750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 55620870144.0000 - mae: 206172.7344 - val_loss: 56284930048.0000 - val_mae: 206976.7500
Epoch 10/50
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 55528820736.0000 - mae: 206044.4844

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 55509204992.0000 - mae: 205990.0156 - val_loss: 56180420608.0000 - val_mae: 206801.7500
Epoch 11/50
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 55468081152.0000 - mae: 205939.1875

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 55387095040.0000 - mae: 205789.0156 - val_loss: 56061485056.0000 - val_mae: 206610.7031
Epoch 12/50
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 55304876032.0000 - mae: 205668.8750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 55258509312.0000 - mae: 205578.1094 - val_loss: 55939403776.0000 - val_mae: 206418.8906
Epoch 13/50
428/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 55317782528.0000 - mae: 205711.0156

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 55120134144.0000 - mae: 205350.0000 - val_loss: 55790252032.0000 - val_mae: 206151.2344
Epoch 14/50
435/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 55065661440.0000 - mae: 205288.9844

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 54977081344.0000 - mae: 205111.7031 - val_loss: 55651229696.0000 - val_mae: 205923.8125
Epoch 15/50
439/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 54823321600.0000 - mae: 204877.3906

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 54821093376.0000 - mae: 204852.4375 - val_loss: 55511302144.0000 - val_mae: 205700.2500
Epoch 16/50
440/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 54679117824.0000 - mae: 204620.2188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 54662287360.0000 - mae: 204588.3750 - val_loss: 55310565376.0000 - val_mae: 205348.7969
Epoch 17/50
433/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 54626893824.0000 - mae: 204549.0312

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 54493835264.0000 - mae: 204308.0625 - val_loss: 55158657024.0000 - val_mae: 205117.5469
Epoch 18/50
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 54401265664.0000 - mae: 204169.8906

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 54320697344.0000 - mae: 204018.9688 - val_loss: 54951120896.0000 - val_mae: 204727.1875
Epoch 19/50
430/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 54317080576.0000 - mae: 204047.7500

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 54139621376.0000 - mae: 203710.7969 - val_loss: 54805544960.0000 - val_mae: 204509.1875
Epoch 20/50
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 53992865792.0000 - mae: 203477.2969

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 53946634240.0000 - mae: 203385.9219 - val_loss: 54583484416.0000 - val_mae: 204127.6562
Epoch 21/50
440/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 53765496832.0000 - mae: 203086.2031

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53748981760.0000 - mae: 203054.6094 - val_loss: 54402985984.0000 - val_mae: 203820.7656
Epoch 22/50
422/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 53699629056.0000 - mae: 202995.0000

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53547499520.0000 - mae: 202711.2812 - val_loss: 54175363072.0000 - val_mae: 203404.7500
Epoch 23/50
431/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 53463621632.0000 - mae: 202588.3438

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53333045248.0000 - mae: 202351.7031 - val_loss: 53992177664.0000 - val_mae: 203104.2969
Epoch 24/50
428/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53306957824.0000 - mae: 202337.4375

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53112377344.0000 - mae: 201974.5625 - val_loss: 53806116864.0000 - val_mae: 202810.4375
Epoch 25/50
440/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 52905721856.0000 - mae: 201623.4844

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52889272320.0000 - mae: 201591.7500 - val_loss: 53523226624.0000 - val_mae: 202306.4062
Epoch 26/50
427/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52845453312.0000 - mae: 201547.9844

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52663037952.0000 - mae: 201199.9531 - val_loss: 53279248384.0000 - val_mae: 201869.5469
Epoch 27/50
430/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 52600672256.0000 - mae: 201126.6562

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52427137024.0000 - mae: 200790.7500 - val_loss: 53093396480.0000 - val_mae: 201537.0000
Epoch 28/50
411/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 52291383296.0000 - mae: 200503.7031

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52173791232.0000 - mae: 200362.9062 - val_loss: 52798111744.0000 - val_mae: 201015.4375
Epoch 29/50
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51929751552.0000 - mae: 199964.2031

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51910848512.0000 - mae: 199910.1094 - val_loss: 52600213504.0000 - val_mae: 200730.0938
Epoch 30/50
439/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51671859200.0000 - mae: 199513.2188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51669323776.0000 - mae: 199488.0000 - val_loss: 52298743808.0000 - val_mae: 200160.7500
Epoch 31/50
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51493171200.0000 - mae: 199186.5469

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51414601728.0000 - mae: 199035.4688 - val_loss: 52007952384.0000 - val_mae: 199593.2344
Epoch 32/50
439/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51120214016.0000 - mae: 198551.6562

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51117867008.0000 - mae: 198526.4219 - val_loss: 51818909696.0000 - val_mae: 199335.8906
Epoch 33/50
418/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50975531008.0000 - mae: 198257.7656

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50861101056.0000 - mae: 198069.3594 - val_loss: 51496464384.0000 - val_mae: 198701.6562
Epoch 34/50
409/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50745528320.0000 - mae: 197843.6875

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50567348224.0000 - mae: 197558.8438 - val_loss: 51219312640.0000 - val_mae: 198183.2969
Epoch 35/50
420/441 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50437885952.0000 - mae: 197330.2188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50282999808.0000 - mae: 197048.4062 - val_loss: 50828562432.0000 - val_mae: 197516.8281
Epoch 36/50
439/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49977651200.0000 - mae: 196538.1719

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49975361536.0000 - mae: 196513.4062 - val_loss: 50636914688.0000 - val_mae: 197150.9062
Epoch 37/50
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49742143488.0000 - mae: 196115.1406

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49665204224.0000 - mae: 195963.4375 - val_loss: 50340360192.0000 - val_mae: 196651.2344
Epoch 38/50
439/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49369001984.0000 - mae: 195458.4688

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49366929408.0000 - mae: 195433.5312 - val_loss: 49985441792.0000 - val_mae: 195942.4219
Epoch 39/50
440/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49066192896.0000 - mae: 194890.1875

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49050472448.0000 - mae: 194858.5156 - val_loss: 49682178048.0000 - val_mae: 195509.0000
Epoch 40/50
421/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 48892932096.0000 - mae: 194574.8750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48751050752.0000 - mae: 194313.6562 - val_loss: 49326329856.0000 - val_mae: 194856.6094
Epoch 41/50
440/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 48432320512.0000 - mae: 193749.1562

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48416821248.0000 - mae: 193717.5625 - val_loss: 48971575296.0000 - val_mae: 194155.1094
Epoch 42/50
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 48094031872.0000 - mae: 193122.2031

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48094031872.0000 - mae: 193122.2031 - val_loss: 48716427264.0000 - val_mae: 193711.7031
Epoch 43/50
413/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 47847743488.0000 - mae: 192618.0156

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 47762444288.0000 - mae: 192522.9375 - val_loss: 48382492672.0000 - val_mae: 193177.7969
Epoch 44/50
428/441 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 47609958400.0000 - mae: 192273.9062

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 47423561728.0000 - mae: 191903.9844 - val_loss: 48045056000.0000 - val_mae: 192505.2500
Epoch 45/50
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 47048998912.0000 - mae: 191233.8281

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 47048998912.0000 - mae: 191233.8281 - val_loss: 47721992192.0000 - val_mae: 191930.0156
Epoch 46/50
440/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 46717374464.0000 - mae: 190598.8594

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 46702088192.0000 - mae: 190567.2344 - val_loss: 47307689984.0000 - val_mae: 191043.9844
Epoch 47/50
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 46497157120.0000 - mae: 190206.1094

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 46350553088.0000 - mae: 189920.2969 - val_loss: 46840762368.0000 - val_mae: 190281.9219
Epoch 48/50
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 46074953728.0000 - mae: 189417.0469

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 45998428160.0000 - mae: 189262.0312 - val_loss: 46645891072.0000 - val_mae: 189915.7500
Epoch 49/50
435/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 45741047808.0000 - mae: 188798.4531

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 45657227264.0000 - mae: 188614.4531 - val_loss: 46326034432.0000 - val_mae: 189205.7344
Epoch 50/50
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 45428211712.0000 - mae: 188195.8750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 45282013184.0000 - mae: 187909.2344 - val_loss: 45848993792.0000 - val_mae: 188360.2812
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

2026/10/25 01:51:50 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/10/25 01:51:50 INFO mlflow.utils.uv_utils: Detected uv project: found uv.lock and pyproject.toml in c:\syed_taha\ds-october-2026\week2
2026/10/25 01:51:50 INFO mlflow.utils.environment: Detected uv project at c:\syed_taha\ds-october-2026\week2. Attempting to export requirements via 'uv export'.
2026/10/25 01:51:50 INFO mlflow.utils.uv_utils: Exported 151 dependencies via uv
2026/10/25 01:51:50 INFO mlflow.utils.environment: Successfully exported 151 requirements from uv project. Skipping package capture based inference.
2026/10/25 01:51:51 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

In [162]:
import mlflow

runs = mlflow.search_runs(
    experiment_names=["w2-syed-taha"],
    order_by=["metrics.val_loss ASC"],
)

cols = ["run_id", "tags.mlflow.runName", "params.epochs",
        "metrics.val_loss", "metrics.val_mae"]
print(runs[cols].head(6))

best = runs.iloc[0]
print("\nBEST MODEL")
print("Run name :", best["tags.mlflow.runName"])
print("Epochs   :", best["params.epochs"])
print("val_loss :", best["metrics.val_loss"])
print("val_mae  :", best["metrics.val_mae"])

# Save the best model
best_model = mlflow.tensorflow.load_model(f"runs:/{best['run_id']}/model")
best_model.save("best_model.keras")
print("Saved:", best["tags.mlflow.runName"], "-> best_model.keras")

                             run_id   tags.mlflow.runName params.epochs  \
0  85d6ed43fca644618a71a27327092d93       mlp-deeper-50ep            50
1  739dd5009e0046009751b5cda7816176       mlp-deeper-30ep            30
2  a57fc68f0b564ddcb383a7a92ef47203     mlp-baseline-50ep            50
3  a67146a2fb8448a99c49635a1aa96e8d     mlp-baseline-30ep            30
4  ff9c1fb485ae41efb35eccf44238b918  mlp-regularised-50ep            50
5  681dc855c75a4c63a6f38d8b436401c9  mlp-regularised-30ep            30

   metrics.val_loss  metrics.val_mae
0      4.175554e+09     44919.332031
1      4.335154e+09     46067.835938
2      4.660401e+09     48321.851562
3      4.949495e+09     49817.218750
4      4.584899e+10    188360.281250
5      5.228178e+10    200298.046875

BEST MODEL
Run name : mlp-deeper-50ep
Epochs   : 50
val_loss : 4175553536.0
val_mae  : 44919.33203125
Saved: mlp-deeper-50ep -> best_model.keras

In [163]:
import joblib

# Save the fitted scaler
joblib.dump(scaler, "scaler.pkl")
print("Scaler saved successfully!")

Scaler saved successfully!