In [72]:
import pandas as pd

In [73]:
df_housing=pd.read_csv("housing.csv")

In [74]:
df_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [75]:
df_housing.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [76]:
df_housing.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [77]:
median=df_housing['total_bedrooms'].median()

In [78]:
df_housing['total_bedrooms']=df_housing['total_bedrooms'].fillna(median)

In [79]:
df_housing['total_bedrooms'].isnull().sum()

np.int64(0)

In [80]:
df_housing=pd.get_dummies(df_housing,columns=['ocean_proximity'])

In [81]:
df_housing.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
20635    False
20636    False
20637    False
20638    False
20639    False
Length: 20640, dtype: bool

In [82]:
df_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,False,False,False,True,False
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,False,False,False,True,False
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,False,False,False,True,False
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,False,False,False,True,False
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,False,True,False,False,False
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,False,True,False,False,False
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,False,True,False,False,False
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,False,True,False,False,False
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,False,True,False,False,False

In [83]:
ocean_cols = [
    'ocean_proximity_<1H OCEAN',
    'ocean_proximity_INLAND',
    'ocean_proximity_ISLAND',
    'ocean_proximity_NEAR BAY',
    'ocean_proximity_NEAR OCEAN'
]

df_housing[ocean_cols]=df_housing[ocean_cols].astype(int)

In [84]:
df_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,0,0,0,1,0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,0,0,0,1,0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,0,0,0,1,0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,0,0,0,1,0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,0,1,0,0,0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,0,1,0,0,0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,0,1,0,0,0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,0,1,0,0,0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,0,1,0,0,0

In [85]:
df_housing.dtypes

longitude                     float64
latitude                      float64
housing_median_age            float64
total_rooms                   float64
total_bedrooms                float64
population                    float64
households                    float64
median_income                 float64
median_house_value            float64
ocean_proximity_<1H OCEAN       int64
ocean_proximity_INLAND          int64
ocean_proximity_ISLAND          int64
ocean_proximity_NEAR BAY        int64
ocean_proximity_NEAR OCEAN      int64
dtype: object

In [86]:
from sklearn.model_selection import train_test_split

features=['longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income']+ocean_cols

X=df_housing[features]
y=df_housing['median_house_value']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

print(X_train.shape)
print(X_test.shape)

(16512, 13)
(4128, 13)

In [87]:
print(X_test.head(2))
print(y_test.head(2))

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
20046    -119.01     36.06                25.0       1505.0           435.0
3024     -119.46     35.14                30.0       2943.0           435.0

       population  households  median_income  ocean_proximity_<1H OCEAN  \
20046      1392.0       359.0         1.6812                          0
3024       1565.0       584.0         2.5313                          0

       ocean_proximity_INLAND  ocean_proximity_ISLAND  \
20046                       1                       0
3024                        1                       0

       ocean_proximity_NEAR BAY  ocean_proximity_NEAR OCEAN
20046                         0                           0
3024                          0                           0
20046    47700.0
3024     45800.0
Name: median_house_value, dtype: float64

In [88]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)    
X_test = scaler.transform(X_test)

BASE LINE with 30 Epochs and batch size is 30

In [89]:
#from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import Dense, Input

# Model 1: Baseline MLP (Modern & Clean Way)
#model_baseline = Sequential([
 #   Input(shape=(X_train.shape[1],)),  # Yeh pehli line mein input define kar diya
  #  Dense(64, activation='relu'),
   # Dense(32, activation='relu'),
    #Dense(1)  # Regression ke liye 1 output
#])

#model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
#history_baseline = model_baseline.fit(X_train, y_train, validation_split=0.2, epochs=30, batch_size=30, verbose=1)

In [90]:
#import matplotlib.pyplot as plt

#h = history_baseline.history

#plt.figure(figsize=(12, 4))

# 1. Loss (MSE)
#plt.subplot(1, 2, 1)
#plt.plot(h['loss'], label='Train loss')
#plt.plot(h['val_loss'], label='Validation loss')
#plt.title('Baseline MLP: Loss (MSE)')
#plt.xlabel('Epoch')
#plt.ylabel('Loss')
#plt.legend()

# 2. MAE
#plt.subplot(1, 2, 2)
#plt.plot(h['mae'], label='Train MAE')
#plt.plot(h['val_mae'], label='Validation MAE')
#plt.title('Baseline MLP: MAE')
#plt.xlabel('Epoch')
#plt.ylabel('MAE ($)')
#plt.legend()

#plt.tight_layout()
#plt.show()

BASE LINE WITH 50 EPOCHS AND BATCH SIZE IS 50

In [91]:
#from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import Dense, Input

# Model 1: Baseline MLP (Modern & Clean Way)
#model_baseline = Sequential([
 #   Input(shape=(X_train.shape[1],)),  # Yeh pehli line mein input define kar diya
  #  Dense(64, activation='relu'),
   # Dense(32, activation='relu'),
    #Dense(1)  # Regression ke liye 1 output
#])

#model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
#history_baseline = model_baseline.fit(X_train, y_train, validation_split=0.2, epochs=50, batch_size=50, verbose=1)

2) Deeper DNN (MULTIPLE LAYERS)

In [92]:
#from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import Dense, Input

# Model 1: Baseline MLP (Modern & Clean Way)
#model_baseline = Sequential([
 #   Input(shape=(X_train.shape[1],)),  # Yeh pehli line mein input define kar diya
  #  Dense(128, activation='relu'),
   # Dense(64, activation='relu'),
    #Dense(32, activation='relu'),
    #Dense(16, activation='relu'),
    #Dense(1)  # Regression ke liye 1 output
#])

#model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
#history_baseline = model_baseline.fit(X_train, y_train, validation_split=0.2, epochs=50, batch_size=50, verbose=1)

now with 75 epochs with 75 batch size

In [93]:
#from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import Dense, Input

# Model 1: Baseline MLP (Modern & Clean Way)
#model_baseline = Sequential([
 #   Input(shape=(X_train.shape[1],)),  # Yeh pehli line mein input define kar diya
  #  Dense(128, activation='relu'),
   # Dense(64, activation='relu'),
    #Dense(32, activation='relu'),
    #Dense(16, activation='relu'),
    #Dense(1)  # Regression ke liye 1 output
#])

#model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
#history_baseline = model_baseline.fit(X_train, y_train, validation_split=0.2, epochs=75, batch_size=75, verbose=1)

3)Regularised DNN

In [94]:
#from tensorflow.keras.layers import Dropout, BatchNormalization
#from tensorflow.keras.callbacks import EarlyStopping

# Model 3: Regularised DNN
#model_regularised = Sequential([
 #   Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
  #  BatchNormalization(),
   # Dropout(0.1), # 30% neurons drop kar dega taake overfit na ho
    #Dense(32, activation='relu'),
    #BatchNormalization(),
    #Dropout(0.2),
    #Dense(1)
#])

#model_regularised.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# Early stopping callback
#early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

#history_reg = model_regularised.fit(
 #   X_train, y_train, 
  #  validation_split=0.2, 
   # epochs=50, 
    #batch_size=32, 
    #callbacks=[early_stop],
    #verbose=1
#)

In [95]:
import mlflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, Input
from tensorflow.keras.callbacks import EarlyStopping

# 1. MLflow Experiment Set karein
mlflow.set_experiment("w2-syed-taha")
mlflow.autolog()

# ==========================================
# 1. BASELINE MLP
# ==========================================
with mlflow.start_run(run_name="mlp-baseline"):
    model_baseline = Sequential([
        Input(shape=(X_train.shape[1],)),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(1)
    ])
    model_baseline.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    
    history_baseline = model_baseline.fit(
        X_train, y_train, 
        validation_split=0.2, 
        epochs=30, 
        batch_size=30,
        verbose=1
    )
    mlflow.log_param("model_type", "Baseline MLP")


# ==========================================
# 2. DEEPER DNN
# ==========================================
with mlflow.start_run(run_name="mlp-deeper"):
    model_deeper = Sequential([
        Input(shape=(X_train.shape[1],)),
        Dense(128, activation='relu'),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(16, activation='relu'),
        Dense(1)
    ])
    model_deeper.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    
    history_deeper = model_deeper.fit(
        X_train, y_train, 
        validation_split=0.2, 
        epochs=50, 
        batch_size=50, 
        verbose=1
    )
    mlflow.log_param("model_type", "Deeper DNN")


# ==========================================
# 3. REGULARISED DNN
# ==========================================
with mlflow.start_run(run_name="mlp-regularised"):
    model_regularised = Sequential([
        Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        BatchNormalization(),
        Dropout(0.1),
        Dense(32, activation='relu'),
        BatchNormalization(),
        Dropout(0.2),
        Dense(1)
    ])
    model_regularised.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    
    early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
    
    history_reg = model_regularised.fit(
        X_train, y_train, 
        validation_split=0.2, 
        epochs=50, 
        batch_size=32, 
        callbacks=[early_stop],
        verbose=1
    )
    mlflow.log_param("model_type", "Regularised DNN")

print("All three models have successfully run and been logged in MLflow!")

2026/10/23 15:59:36 WARNING mlflow.utils.autologging_utils: MLflow keras autologging is known to be compatible with 3.7.0 <= keras, but the installed version is 3.16.0.dev2026101803. If you encounter errors during autologging, try upgrading / downgrading keras to a compatible version, or try upgrading MLflow.
2026/10/23 15:59:36 INFO mlflow.tracking.fluent: Autologging successfully enabled for keras.
2026/10/23 15:59:36 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2026/10/23 15:59:36 WARNING mlflow.utils.autologging_utils: MLflow tensorflow autologging is known to be compatible with 2.17.1 <= tensorflow, but the installed version is 2.22.0-rc0. If you encounter errors during autologging, try upgrading / downgrading tensorflow to a compatible version, or try upgrading MLflow.
2026/10/23 15:59:36 INFO mlflow.tracking.fluent: Autologging successfully enabled for tensorflow.
2026/10/23 15:59:37 WARNING mlflow.tensorflow: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'

Epoch 1/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 55973806080.0000 - mae: 206630.2344

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 22s 21ms/step - loss: 55973806080.0000 - mae: 206630.2344 - val_loss: 56104046592.0000 - val_mae: 206303.2344
Epoch 2/30
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 53391675392.0000 - mae: 201183.7656

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 25s 12ms/step - loss: 53287059456.0000 - mae: 200975.6719 - val_loss: 50802569216.0000 - val_mae: 195105.4844
Epoch 3/30
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 45150093312.0000 - mae: 182886.4062

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 45107257344.0000 - mae: 182767.1562 - val_loss: 39776055296.0000 - val_mae: 169534.2188
Epoch 4/30
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32729837568.0000 - mae: 151205.9375

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - loss: 32687546368.0000 - mae: 151057.2344 - val_loss: 26620903424.0000 - val_mae: 133011.1250
Epoch 5/30
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 20844015616.0000 - mae: 114443.8594

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 20764356608.0000 - mae: 114147.4922 - val_loss: 16491103232.0000 - val_mae: 98435.4844
Epoch 6/30
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13344032768.0000 - mae: 88206.2344

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 13271270400.0000 - mae: 87903.0078 - val_loss: 11494766592.0000 - val_mae: 80293.3125
Epoch 7/30
424/441 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10222734336.0000 - mae: 77061.9141

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 10158932992.0000 - mae: 76752.8438 - val_loss: 9717833728.0000 - val_mae: 73595.8750
Epoch 8/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9021607936.0000 - mae: 71937.5469

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9021607936.0000 - mae: 71937.5469 - val_loss: 8917790720.0000 - val_mae: 70200.6016
Epoch 9/30
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8399545856.0000 - mae: 68771.7812

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 8394535936.0000 - mae: 68749.9531 - val_loss: 8356748800.0000 - val_mae: 67565.1484
Epoch 10/30
438/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7919091712.0000 - mae: 66177.5625

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 7914459648.0000 - mae: 66154.6797 - val_loss: 7898128384.0000 - val_mae: 65289.6055
Epoch 11/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7510173696.0000 - mae: 63943.8086

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - loss: 7510173696.0000 - mae: 63943.8086 - val_loss: 7505833472.0000 - val_mae: 63290.0625
Epoch 12/30
434/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7177041920.0000 - mae: 62095.7539

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 7157342720.0000 - mae: 62007.9297 - val_loss: 7161972224.0000 - val_mae: 61475.2227
Epoch 13/30
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6855757824.0000 - mae: 60324.0391

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 6843451904.0000 - mae: 60266.6523 - val_loss: 6857158144.0000 - val_mae: 59815.1406
Epoch 14/30
434/441 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6578506240.0000 - mae: 58771.8867

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 6561362944.0000 - mae: 58693.4375 - val_loss: 6584271872.0000 - val_mae: 58301.9570
Epoch 15/30
439/441 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6304764928.0000 - mae: 57280.2656

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 6307102208.0000 - mae: 57280.6094 - val_loss: 6340668416.0000 - val_mae: 56991.9219
Epoch 16/30
433/441 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6095668224.0000 - mae: 56110.0664

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 6077999104.0000 - mae: 56033.5430 - val_loss: 6122570752.0000 - val_mae: 55838.8633
Epoch 17/30
439/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5868861952.0000 - mae: 54920.3203

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 5871547904.0000 - mae: 54923.1914 - val_loss: 5928224768.0000 - val_mae: 54794.7148
Epoch 18/30
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5698436096.0000 - mae: 53995.2891

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5687397888.0000 - mae: 53947.8516 - val_loss: 5758517248.0000 - val_mae: 53876.0703
Epoch 19/30
441/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5526317568.0000 - mae: 53113.0078

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5526317568.0000 - mae: 53113.0078 - val_loss: 5612627456.0000 - val_mae: 53090.1055
Epoch 20/30
434/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5399489024.0000 - mae: 52462.2852

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5388125696.0000 - mae: 52410.8633 - val_loss: 5490319872.0000 - val_mae: 52464.8945
Epoch 21/30
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5278386176.0000 - mae: 51863.7969

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 5270792704.0000 - mae: 51828.2930 - val_loss: 5387401216.0000 - val_mae: 51949.5820
Epoch 22/30
437/441 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5178059776.0000 - mae: 51378.6836

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5170704896.0000 - mae: 51344.9570 - val_loss: 5300906496.0000 - val_mae: 51525.2109
Epoch 23/30
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5101656064.0000 - mae: 51002.2305

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5085192704.0000 - mae: 50933.7227 - val_loss: 5229585408.0000 - val_mae: 51169.2539
Epoch 24/30
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5028676096.0000 - mae: 50650.5781

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 5012533760.0000 - mae: 50583.0586 - val_loss: 5169794048.0000 - val_mae: 50867.9570
Epoch 25/30
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4958560256.0000 - mae: 50313.5156

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4950206464.0000 - mae: 50281.0000 - val_loss: 5118716416.0000 - val_mae: 50618.9883
Epoch 26/30
435/441 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4901036544.0000 - mae: 50046.8125

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 4896392192.0000 - mae: 50017.0938 - val_loss: 5074892288.0000 - val_mae: 50403.2344
Epoch 27/30
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4864595968.0000 - mae: 49852.5820

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 4848976896.0000 - mae: 49782.7852 - val_loss: 5036407808.0000 - val_mae: 50212.0430
Epoch 28/30
432/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4822223872.0000 - mae: 49642.3008

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4806717952.0000 - mae: 49571.0352 - val_loss: 5002250240.0000 - val_mae: 50040.4062
Epoch 29/30
427/441 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4780492800.0000 - mae: 49449.8242

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4768838656.0000 - mae: 49378.8945 - val_loss: 4971871744.0000 - val_mae: 49893.9180
Epoch 30/30
436/441 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4742672896.0000 - mae: 49237.3984

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

441/441 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4734835200.0000 - mae: 49204.1055 - val_loss: 4944717312.0000 - val_mae: 49764.1484
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

2026/10/23 16:02:15 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/10/23 16:02:16 INFO mlflow.utils.uv_utils: Detected uv project: found uv.lock and pyproject.toml in c:\syed_taha\ds-october-2026\week2
2026/10/23 16:02:16 INFO mlflow.utils.environment: Detected uv project at c:\syed_taha\ds-october-2026\week2. Attempting to export requirements via 'uv export'.
2026/10/23 16:02:16 INFO mlflow.utils.uv_utils: Exported 151 dependencies via uv
2026/10/23 16:02:16 INFO mlflow.utils.environment: Successfully exported 151 requirements from uv project. Skipping package capture based inference.
2026/10/23 16:02:16 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/10/23 16:02:17 WARNING mlflow.tensorflow: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'

Epoch 1/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 48531603456.0000 - mae: 187783.0469

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 48531603456.0000 - mae: 187783.0469 - val_loss: 17195313152.0000 - val_mae: 98445.3906
Epoch 2/50
264/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8870672384.0000 - mae: 69598.0547

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8866378752.0000 - mae: 69582.1953 - val_loss: 7390154752.0000 - val_mae: 61579.6172
Epoch 3/50
259/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6547059200.0000 - mae: 58209.9531

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6517626880.0000 - mae: 58057.3555 - val_loss: 6175331840.0000 - val_mae: 55272.9141
Epoch 4/50
264/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5655331840.0000 - mae: 53519.7383

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5652753920.0000 - mae: 53508.2383 - val_loss: 5561771008.0000 - val_mae: 52165.7031
Epoch 5/50
261/265 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5201666048.0000 - mae: 51361.3242

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5193661440.0000 - mae: 51313.3672 - val_loss: 5245771264.0000 - val_mae: 50714.5898
Epoch 6/50
256/265 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4956227072.0000 - mae: 50228.9062

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 4937948160.0000 - mae: 50109.0586 - val_loss: 5060993024.0000 - val_mae: 49872.9062
Epoch 7/50
252/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4801466880.0000 - mae: 49466.3125

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4773348352.0000 - mae: 49278.1211 - val_loss: 4938725376.0000 - val_mae: 49305.7188
Epoch 8/50
261/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4662992896.0000 - mae: 48710.4062

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4657445888.0000 - mae: 48667.1875 - val_loss: 4849594368.0000 - val_mae: 48903.4062
Epoch 9/50
259/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4585592320.0000 - mae: 48292.8789

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 4571005952.0000 - mae: 48194.4570 - val_loss: 4781176832.0000 - val_mae: 48589.6836
Epoch 10/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4504232448.0000 - mae: 47814.1133

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4504232448.0000 - mae: 47814.1133 - val_loss: 4726905344.0000 - val_mae: 48347.0508
Epoch 11/50
253/265 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4465718784.0000 - mae: 47625.3633

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4449304576.0000 - mae: 47494.3086 - val_loss: 4681181696.0000 - val_mae: 48132.0117
Epoch 12/50
259/265 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4417393152.0000 - mae: 47306.5547

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 4403442688.0000 - mae: 47217.4844 - val_loss: 4642991104.0000 - val_mae: 47944.1562
Epoch 13/50
264/265 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4366626816.0000 - mae: 46981.1797

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 4365677056.0000 - mae: 46978.2539 - val_loss: 4611010048.0000 - val_mae: 47780.5977
Epoch 14/50
262/265 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4341494272.0000 - mae: 46801.8633

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 4333382656.0000 - mae: 46768.5547 - val_loss: 4583488512.0000 - val_mae: 47636.7812
Epoch 15/50
259/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4318761984.0000 - mae: 46671.2070

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4304914432.0000 - mae: 46584.9258 - val_loss: 4559152640.0000 - val_mae: 47501.2383
Epoch 16/50
263/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4278452992.0000 - mae: 46407.5586

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4279515904.0000 - mae: 46422.1992 - val_loss: 4537997312.0000 - val_mae: 47378.6641
Epoch 17/50
251/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4271062784.0000 - mae: 46379.6719

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4256873984.0000 - mae: 46276.8711 - val_loss: 4519592960.0000 - val_mae: 47266.2188
Epoch 18/50
263/265 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4235791360.0000 - mae: 46131.5508

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4236937472.0000 - mae: 46147.0469 - val_loss: 4502710784.0000 - val_mae: 47156.6836
Epoch 19/50
262/265 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4226190080.0000 - mae: 46056.2656

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 4218751488.0000 - mae: 46028.6602 - val_loss: 4487505408.0000 - val_mae: 47056.2617
Epoch 20/50
253/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4213856768.0000 - mae: 46030.0234

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4201810176.0000 - mae: 45920.4766 - val_loss: 4473481728.0000 - val_mae: 46964.4141
Epoch 21/50
259/265 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4200226560.0000 - mae: 45910.1602

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4186333696.0000 - mae: 45821.6094 - val_loss: 4460940288.0000 - val_mae: 46880.5117
Epoch 22/50
259/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4185818624.0000 - mae: 45817.6484

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4171917568.0000 - mae: 45728.6875 - val_loss: 4449257984.0000 - val_mae: 46798.8320
Epoch 23/50
257/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4182126592.0000 - mae: 45781.0664

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4158118144.0000 - mae: 45642.9062 - val_loss: 4438373376.0000 - val_mae: 46725.8945
Epoch 24/50
257/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4169226752.0000 - mae: 45700.0000

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4145357824.0000 - mae: 45562.0117 - val_loss: 4428268544.0000 - val_mae: 46659.0703
Epoch 25/50
254/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4141529856.0000 - mae: 45577.7305

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4133595136.0000 - mae: 45487.9414 - val_loss: 4419115008.0000 - val_mae: 46595.0078
Epoch 26/50
256/265 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4131079680.0000 - mae: 45504.7266

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 4122752256.0000 - mae: 45417.5508 - val_loss: 4410636800.0000 - val_mae: 46531.6914
Epoch 27/50
263/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4111073792.0000 - mae: 45331.9805

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4112621568.0000 - mae: 45350.0312 - val_loss: 4402976256.0000 - val_mae: 46475.1445
Epoch 28/50
256/265 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4111615488.0000 - mae: 45376.9883

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 4103322624.0000 - mae: 45288.8164 - val_loss: 4395619328.0000 - val_mae: 46418.5703
Epoch 29/50
259/265 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4108219392.0000 - mae: 45320.6484

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 4094484480.0000 - mae: 45229.6328 - val_loss: 4388569088.0000 - val_mae: 46365.8945
Epoch 30/50
258/265 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4103816704.0000 - mae: 45295.9414

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 4086102784.0000 - mae: 45172.9336 - val_loss: 4381712896.0000 - val_mae: 46315.3320
Epoch 31/50
257/265 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4101113344.0000 - mae: 45255.1211

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4078198528.0000 - mae: 45117.7461 - val_loss: 4375271936.0000 - val_mae: 46267.4375
Epoch 32/50
259/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4084200192.0000 - mae: 45155.8906

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4070592768.0000 - mae: 45064.5391 - val_loss: 4369057280.0000 - val_mae: 46220.6055
Epoch 33/50
256/265 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4071728384.0000 - mae: 45104.0117

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4063534080.0000 - mae: 45015.4844 - val_loss: 4363304960.0000 - val_mae: 46178.9492
Epoch 34/50
250/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4058002176.0000 - mae: 45004.9805

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4056574976.0000 - mae: 44964.6680 - val_loss: 4357650432.0000 - val_mae: 46135.0742
Epoch 35/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4049861376.0000 - mae: 44917.5781

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4049861376.0000 - mae: 44917.5781 - val_loss: 4352117248.0000 - val_mae: 46092.5938
Epoch 36/50
258/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4060339200.0000 - mae: 44990.9648

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4043184384.0000 - mae: 44869.7852 - val_loss: 4346389504.0000 - val_mae: 46049.8711
Epoch 37/50
255/265 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4051144448.0000 - mae: 44937.6680

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 4036809472.0000 - mae: 44823.8008 - val_loss: 4341005312.0000 - val_mae: 46007.9883
Epoch 38/50
262/265 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4036193024.0000 - mae: 44796.0312

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 4030369536.0000 - mae: 44777.9492 - val_loss: 4335698944.0000 - val_mae: 45967.5117
Epoch 39/50
262/265 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4030017536.0000 - mae: 44752.5508

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 4024264448.0000 - mae: 44734.9492 - val_loss: 4330294784.0000 - val_mae: 45927.5742
Epoch 40/50
262/265 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4023696384.0000 - mae: 44706.5273

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 4018012160.0000 - mae: 44689.4102 - val_loss: 4325072896.0000 - val_mae: 45887.0312
Epoch 41/50
263/265 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4009767168.0000 - mae: 44623.6797

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 4011853312.0000 - mae: 44644.9336 - val_loss: 4319861248.0000 - val_mae: 45845.3086
Epoch 42/50
260/265 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4012673280.0000 - mae: 44642.2188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 4005807616.0000 - mae: 44602.1328 - val_loss: 4314504192.0000 - val_mae: 45805.5820
Epoch 43/50
262/265 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4005125888.0000 - mae: 44572.0859

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 3999654400.0000 - mae: 44556.4297 - val_loss: 4309425664.0000 - val_mae: 45765.1094
Epoch 44/50
262/265 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3998695168.0000 - mae: 44526.5430

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 3993293056.0000 - mae: 44511.3398 - val_loss: 4303670272.0000 - val_mae: 45720.8789
Epoch 45/50
261/265 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3989435648.0000 - mae: 44490.6133

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 3986674432.0000 - mae: 44463.3516 - val_loss: 4298028032.0000 - val_mae: 45675.5664
Epoch 46/50
258/265 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3995922176.0000 - mae: 44530.5508

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 3979663616.0000 - mae: 44413.4219 - val_loss: 4292043264.0000 - val_mae: 45631.7539
Epoch 47/50
262/265 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3977440256.0000 - mae: 44376.4258

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3972233216.0000 - mae: 44362.3633 - val_loss: 4285553920.0000 - val_mae: 45587.3438
Epoch 48/50
264/265 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3964146432.0000 - mae: 44304.5625

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3964452352.0000 - mae: 44308.0898 - val_loss: 4278737664.0000 - val_mae: 45539.9883
Epoch 49/50
254/265 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3962887424.0000 - mae: 44334.4531

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3955907328.0000 - mae: 44247.9805 - val_loss: 4270898944.0000 - val_mae: 45486.5469
Epoch 50/50
262/265 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3951856384.0000 - mae: 44199.8008

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

265/265 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3946817280.0000 - mae: 44186.4648 - val_loss: 4262666496.0000 - val_mae: 45427.4258
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

2026/10/23 16:04:08 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/10/23 16:04:08 INFO mlflow.utils.uv_utils: Detected uv project: found uv.lock and pyproject.toml in c:\syed_taha\ds-october-2026\week2
2026/10/23 16:04:08 INFO mlflow.utils.environment: Detected uv project at c:\syed_taha\ds-october-2026\week2. Attempting to export requirements via 'uv export'.
2026/10/23 16:04:08 INFO mlflow.utils.uv_utils: Exported 151 dependencies via uv
2026/10/23 16:04:08 INFO mlflow.utils.environment: Successfully exported 151 requirements from uv project. Skipping package capture based inference.
2026/10/23 16:04:09 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
c:\syed_taha\ds-october-2026\week2\.venv\Lib\site-packages\keras\src\layers\core\dense.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026/10/23 16:04:10 WARNING mlflow.tensorflow: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'

Epoch 1/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 56149049344.0000 - mae: 207011.1094

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 9s 13ms/step - loss: 56149049344.0000 - mae: 207011.1094 - val_loss: 56863928320.0000 - val_mae: 207903.7188
Epoch 2/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 56130662400.0000 - mae: 206986.4219

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 56130662400.0000 - mae: 206986.4219 - val_loss: 56839704576.0000 - val_mae: 207872.3438
Epoch 3/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 56098291712.0000 - mae: 206938.4062

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 56098291712.0000 - mae: 206938.4062 - val_loss: 56798281728.0000 - val_mae: 207807.4062
Epoch 4/50
409/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 56122351616.0000 - mae: 206993.4219

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 56052891648.0000 - mae: 206868.3438 - val_loss: 56748331008.0000 - val_mae: 207731.8906
Epoch 5/50
411/413 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55999188992.0000 - mae: 206810.0312

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 55996256256.0000 - mae: 206779.2812 - val_loss: 56686485504.0000 - val_mae: 207633.7031
Epoch 6/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 55929282560.0000 - mae: 206673.0156

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 55929282560.0000 - mae: 206673.0156 - val_loss: 56618852352.0000 - val_mae: 207529.2188
Epoch 7/50
406/413 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55986188288.0000 - mae: 206791.2344

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 55854166016.0000 - mae: 206551.6875 - val_loss: 56530673664.0000 - val_mae: 207388.2656
Epoch 8/50
403/413 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 55945248768.0000 - mae: 206737.2656

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 55767859200.0000 - mae: 206412.9375 - val_loss: 56437166080.0000 - val_mae: 207233.3906
Epoch 9/50
412/413 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 55668535296.0000 - mae: 206260.6562

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 55674486784.0000 - mae: 206261.9219 - val_loss: 56348217344.0000 - val_mae: 207097.7031
Epoch 10/50
403/413 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 55752482816.0000 - mae: 206424.4375

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 55575367680.0000 - mae: 206099.9844 - val_loss: 56249241600.0000 - val_mae: 206932.0469
Epoch 11/50
408/413 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 55544483840.0000 - mae: 206079.5625

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 55466643456.0000 - mae: 205920.8906 - val_loss: 56128716800.0000 - val_mae: 206738.7344
Epoch 12/50
407/413 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 55469129728.0000 - mae: 205960.2188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 55349968896.0000 - mae: 205730.7344 - val_loss: 56015605760.0000 - val_mae: 206558.6875
Epoch 13/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 55224651776.0000 - mae: 205524.7031

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 55224651776.0000 - mae: 205524.7031 - val_loss: 55890677760.0000 - val_mae: 206353.0156
Epoch 14/50
411/413 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 55099047936.0000 - mae: 205340.2812

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 55095840768.0000 - mae: 205309.2812 - val_loss: 55740190720.0000 - val_mae: 206095.8281
Epoch 15/50
411/413 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 54963646464.0000 - mae: 205117.2031

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 54960312320.0000 - mae: 205085.9844 - val_loss: 55628713984.0000 - val_mae: 205926.3125
Epoch 16/50
407/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 54938419200.0000 - mae: 205082.9531

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 54819893248.0000 - mae: 204853.4062 - val_loss: 55444865024.0000 - val_mae: 205617.1562
Epoch 17/50
406/413 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 54793580544.0000 - mae: 204833.5625

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 54662635520.0000 - mae: 204592.9531 - val_loss: 55295389696.0000 - val_mae: 205377.9062
Epoch 18/50
407/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 54620221440.0000 - mae: 204557.2656

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 54502019072.0000 - mae: 204327.5312 - val_loss: 55146672128.0000 - val_mae: 205121.3594
Epoch 19/50
411/413 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54349230080.0000 - mae: 204091.9688

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 54345564160.0000 - mae: 204060.4844 - val_loss: 55022387200.0000 - val_mae: 204921.8750
Epoch 20/50
408/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 54247501824.0000 - mae: 203930.0625

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - loss: 54170189824.0000 - mae: 203770.7500 - val_loss: 54745108480.0000 - val_mae: 204431.2031
Epoch 21/50
411/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 53999771648.0000 - mae: 203512.3438

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 53996822528.0000 - mae: 203481.7812 - val_loss: 54645542912.0000 - val_mae: 204295.2344
Epoch 22/50
409/413 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53886754816.0000 - mae: 203299.8750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 53818261504.0000 - mae: 203173.9375 - val_loss: 54391033856.0000 - val_mae: 203843.6562
Epoch 23/50
410/413 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53643681792.0000 - mae: 202885.4062

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 53621784576.0000 - mae: 202843.5312 - val_loss: 54238081024.0000 - val_mae: 203628.1250
Epoch 24/50
407/413 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 53550178304.0000 - mae: 202755.8281

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 53433028608.0000 - mae: 202525.7031 - val_loss: 53990363136.0000 - val_mae: 203163.1719
Epoch 25/50
406/413 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53351346176.0000 - mae: 202409.8281

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 53221404672.0000 - mae: 202168.0781 - val_loss: 53791977472.0000 - val_mae: 202837.3906
Epoch 26/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 53015351296.0000 - mae: 201819.5469

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 53015351296.0000 - mae: 201819.5469 - val_loss: 53666574336.0000 - val_mae: 202647.7812
Epoch 27/50
412/413 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52795506688.0000 - mae: 201451.7656

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 52801486848.0000 - mae: 201453.5156 - val_loss: 53384167424.0000 - val_mae: 202133.5781
Epoch 28/50
411/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 52588433408.0000 - mae: 201108.2500

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 52584861696.0000 - mae: 201076.9844 - val_loss: 53228412928.0000 - val_mae: 201938.7812
Epoch 29/50
411/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 52360028160.0000 - mae: 200721.2188

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - loss: 52356726784.0000 - mae: 200690.3750 - val_loss: 52891648000.0000 - val_mae: 201282.1719
Epoch 30/50
410/413 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 52150128640.0000 - mae: 200339.6562

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 52128227328.0000 - mae: 200297.1094 - val_loss: 52688293888.0000 - val_mae: 200918.8125
Epoch 31/50
409/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 51950551040.0000 - mae: 200003.3594

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 51882881024.0000 - mae: 199876.7344 - val_loss: 52429582336.0000 - val_mae: 200510.7812
Epoch 32/50
408/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 51725877248.0000 - mae: 199625.1406

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 51650256896.0000 - mae: 199464.9375 - val_loss: 52227891200.0000 - val_mae: 200150.1719
Epoch 33/50
409/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 51466854400.0000 - mae: 199161.0781

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 51399794688.0000 - mae: 199034.2344 - val_loss: 51907686400.0000 - val_mae: 199576.9219
Epoch 34/50
409/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 51215114240.0000 - mae: 198722.5938

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 51148353536.0000 - mae: 198596.2812 - val_loss: 51760480256.0000 - val_mae: 199333.5469
Epoch 35/50
410/413 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 50902663168.0000 - mae: 198171.3906

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 50881130496.0000 - mae: 198129.1719 - val_loss: 51413295104.0000 - val_mae: 198743.0312
Epoch 36/50
407/413 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 50726391808.0000 - mae: 197892.6406

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 50613170176.0000 - mae: 197663.7031 - val_loss: 51213217792.0000 - val_mae: 198377.1719
Epoch 37/50
406/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 50471022592.0000 - mae: 197433.4375

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 50345033728.0000 - mae: 197192.1562 - val_loss: 50997870592.0000 - val_mae: 198055.7812
Epoch 38/50
407/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 50196275200.0000 - mae: 196944.4531

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 50082643968.0000 - mae: 196715.0156 - val_loss: 50700730368.0000 - val_mae: 197558.3438
Epoch 39/50
412/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 49785151488.0000 - mae: 196199.5312

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 49790492672.0000 - mae: 196200.5781 - val_loss: 50293145600.0000 - val_mae: 196805.3906
Epoch 40/50
412/413 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 49494503424.0000 - mae: 195688.4219

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 49499033600.0000 - mae: 195688.5781 - val_loss: 50079039488.0000 - val_mae: 196390.3906
Epoch 41/50
410/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 49257119744.0000 - mae: 195258.7656

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 49234464768.0000 - mae: 195214.4219 - val_loss: 49610166272.0000 - val_mae: 195489.2812
Epoch 42/50
410/413 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 48939876352.0000 - mae: 194685.9062

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 48917266432.0000 - mae: 194642.4062 - val_loss: 49362235392.0000 - val_mae: 195049.0938
Epoch 43/50
406/413 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 48739192832.0000 - mae: 194347.2656

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 48615460864.0000 - mae: 194103.9062 - val_loss: 49010814976.0000 - val_mae: 194418.3750
Epoch 44/50
408/413 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 48392830976.0000 - mae: 193728.3281

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 48320024576.0000 - mae: 193567.9062 - val_loss: 48833531904.0000 - val_mae: 194150.5781
Epoch 45/50
410/413 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 48016846848.0000 - mae: 193029.7344

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 47994507264.0000 - mae: 192986.5312 - val_loss: 48584241152.0000 - val_mae: 193779.5469
Epoch 46/50
407/413 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 47795896320.0000 - mae: 192646.3750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 47684571136.0000 - mae: 192415.5469 - val_loss: 48154714112.0000 - val_mae: 192842.9219
Epoch 47/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 47373635584.0000 - mae: 191826.8750

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 47373635584.0000 - mae: 191826.8750 - val_loss: 47698706432.0000 - val_mae: 192108.2188
Epoch 48/50
409/413 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 47112523776.0000 - mae: 191368.5938

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 47048212480.0000 - mae: 191241.1406 - val_loss: 47431602176.0000 - val_mae: 191602.5469
Epoch 49/50
412/413 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 46716284928.0000 - mae: 190633.3438

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 46721675264.0000 - mae: 190635.2031 - val_loss: 47135223808.0000 - val_mae: 190917.4688
Epoch 50/50
413/413 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 46401167360.0000 - mae: 190034.9688

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 46401167360.0000 - mae: 190034.9688 - val_loss: 47025893376.0000 - val_mae: 190780.0312
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 303ms/step

2026/10/23 16:07:38 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/10/23 16:07:38 INFO mlflow.utils.uv_utils: Detected uv project: found uv.lock and pyproject.toml in c:\syed_taha\ds-october-2026\week2
2026/10/23 16:07:38 INFO mlflow.utils.environment: Detected uv project at c:\syed_taha\ds-october-2026\week2. Attempting to export requirements via 'uv export'.
2026/10/23 16:07:39 INFO mlflow.utils.uv_utils: Exported 151 dependencies via uv
2026/10/23 16:07:39 INFO mlflow.utils.environment: Successfully exported 151 requirements from uv project. Skipping package capture based inference.
2026/10/23 16:07:39 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

All three models have successfully run and been logged in MLflow!

In [96]:
model_deeper.save("best_model.keras")
print("model saved successfully!")

model saved successfully!

In [97]:
import joblib

# Save the fitted scaler
joblib.dump(scaler, "scaler.pkl")
print("Scaler saved successfully!")

Scaler saved successfully!